#!/bin/sh
# Generated by Chickadee — do not edit. The C++ source below is the
# test; this wrapper locates the submission, compiles one translation
# unit with the injected runtime, and runs it under the ordinary
# shell-script contract.
student_file=""
if [ -f .chickadee_student_module ]; then
    student_file=$(cat .chickadee_student_module)
fi
if [ ! -f "$student_file" ]; then
    for candidate in *.cpp; do
        case "$candidate" in
            .ck_*|*test_*) ;;
            *) student_file="$candidate"; break ;;
        esac
    done
fi
if [ ! -f "$student_file" ]; then
    echo "No C++ submission file was found to grade." 1>&2
    exit 2
fi
cp "$student_file" .ck_solution.cpp
cat > .ck_src_fam_01.cpp <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (p).
// Edit the family, not this file. spec_hash: 373c736715269bba
#include "test_runtime.hpp"
#define main ck_student_main
#include ".ck_solution.cpp"
#undef main
int main() {
    auto x = 1;
    try {
        auto ck_started = std::chrono::steady_clock::now();
        auto result = classify(x);
        double ck_elapsed_ms = std::chrono::duration<double, std::milli>(
            std::chrono::steady_clock::now() - ck_started).count();
        (void)result;
        if (ck_elapsed_ms > 0.5) {
            ck::failed(std::string("too slow\n")
                + "  input:    " + "x=" + ck::format(x) + "\n"
                + "  threshold: " + ck::format(0.5) + " ms\n"
                + "  elapsed:   " + ck::format(ck_elapsed_ms) + " ms");
        }
        ck::passed("Completed in " + ck::format(ck_elapsed_ms) + " ms");
    } catch (const std::exception& ck_e) {
        ck::failed(std::string("unexpected exception\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  error:    " + ck_e.what());
    }
}
CHICKADEE_GENERATED_SOURCE
g++ -std=c++20 -O2 .ck_src_fam_01.cpp -o .ck_bin_fam_01 1>&2 || exit 2
exec ./.ck_bin_fam_01
