#!/bin/sh
# Generated by Chickadee — do not edit. The C++ source below is the
# test; this wrapper locates the submission, compiles one translation
# unit with the injected runtime, and runs it under the ordinary
# shell-script contract.
student_file=""
if [ -f .chickadee_student_module ]; then
    student_file=$(cat .chickadee_student_module)
fi
if [ ! -f "$student_file" ]; then
    # POSIX `*` does not match a leading dot, so every artefact this
    # wrapper writes (.ck_src_*, .ck_bin_*, .ck_solution.cpp) is already
    # invisible here — the `.ck_*` arm this case once carried matched
    # nothing and has been removed rather than left reading as a guard.
    # `*test_*` still skips a hand-written test file.
    for candidate in *.cpp; do
        case "$candidate" in
            *test_*) ;;
            *) student_file="$candidate"; break ;;
        esac
    done
fi
if [ ! -f "$student_file" ]; then
    echo "No C++ submission file was found to grade." 1>&2
    exit 2
fi
cp "$student_file" .ck_solution.cpp
cat > '.ck_src_fam_01.cpp' <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (p).
// Edit the family, not this file. spec_hash: 373c736715269bba
#include "test_runtime.hpp"
#define main ck_student_main
#include ".ck_solution.cpp"
#undef main
int main() {
    auto x = 1;
    try {
        auto ck_started = std::chrono::steady_clock::now();
        classify(x);
        double ck_elapsed_ms = std::chrono::duration<double, std::milli>(
            std::chrono::steady_clock::now() - ck_started).count();
        if (ck_elapsed_ms > 0.5) {
            ck::failed(std::string("too slow\n")
                + "  input:    " + "x=" + ck::format(x) + "\n"
                + "  threshold: " + ck::format(0.5) + " ms\n"
                + "  elapsed:   " + ck::format(ck_elapsed_ms) + " ms");
        }
        ck::passed("Completed in " + ck::format(ck_elapsed_ms) + " ms");
    } catch (const std::exception& ck_e) {
        ck::failed(std::string("unexpected exception\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  error:    " + ck_e.what());
    } catch (...) {
        ck::failed(std::string("unexpected exception\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  error:    (a non-std exception)");
    }
}
CHICKADEE_GENERATED_SOURCE
if ! g++ -std=c++20 -O2 '.ck_src_fam_01.cpp' -o '.ck_bin_fam_01' >.ck_build_log 2>&1; then
    cat .ck_build_log 1>&2
    exit 2
fi
ck_out=$('./.ck_bin_fam_01')
ck_rc=$?
# The sentinel check. Without it, a student's own exit(0) — in an error
# path, which is where an intro submission puts one — exits the binary
# with status 0 and this case, every case, reads as a pass. C++ was the
# only language with no such guard; Java has had one since it shipped.
if ! printf '%s\n' "$ck_out" | grep -q '^CK_SENTINEL$'; then
    echo "The test did not run to completion. Does the submission call exit()?" 1>&2
    exit 2
fi
printf '%s\n' "$ck_out" | grep -v '^CK_SENTINEL$'
exit $ck_rc
