// Plugins/EmbedRunnerSupport/EmbedRunnerSupportPlugin.swift
//
// Compiles `Tools/runner-support/*` into the runner binary at build time.
//
// WHY A PLUGIN AND NOT A RESOURCE BUNDLE. The runner is deployed as a single
// static binary — `Dockerfile` copies `.build/release/chickadee-runner` and
// nothing beside it, and runner hosts are separate machines that upgrade on
// their own schedule. SwiftPM `resources:` would put the helper files in a
// bundle next to the executable, so the binary would stop being self-contained
// and every deployment path (Dockerfile, the prebuilt-artifacts path, the
// systemd unit) would have to learn to carry it. A build-tool plugin emits
// Swift source instead: the bytes end up inside the binary exactly as they did
// when they were hand-typed literals, and nothing about deployment changes.
//
// WHAT IT REPLACES. `Sources/Worker/TestRuntimeSources.swift` was 2,223 lines
// of Swift string literals that mirrored these files by hand, kept honest by a
// drift test comparing the two copies line by line. The copy is gone; the
// canonical files ARE the source now, and drift is not something a test has to
// catch because there is nothing left to drift from.
//
// THE FAILURE MODE THIS KEEPS. `runtimeHelperFiles(for:)` in the Worker is
// still a hand-written exhaustive switch over `AssignmentLanguage`, and that is
// deliberate: it is the compile-forced worklist that made a sixth language
// impossible to forget. This plugin only supplies the bytes it names. A
// language whose canonical file is missing gets an empty source, which
// `RuntimeHelperCoverageTests` fails on — the same "a language is present or it
// is not" rule the vendored-kernel guards apply.

import Foundation
import PackagePlugin

@main
struct EmbedRunnerSupportPlugin: BuildToolPlugin {

    /// Files under `Tools/runner-support/` that are runtime helpers, as opposed
    /// to authoring tools that live in the same directory (`nb_to_r.py`,
    /// `Makefile`).
    ///
    /// DISCOVERED BY SHAPE, not listed: anything named `test_runtime.*` plus
    /// Python's `sitecustomize.py`, which is a runtime helper on exactly the
    /// same terms (the interpreter loads it rather than the test importing it).
    /// A seventh language drops in `test_runtime.<ext>` and is embedded with no
    /// edit here.
    private static func isRuntimeHelper(_ name: String) -> Bool {
        name.hasPrefix("test_runtime.") || name == "sitecustomize.py"
    }

    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {
        let supportDirectory = context.package.directoryURL
            .appending(path: "Tools")
            .appending(path: "runner-support")

        let names = try FileManager.default
            .contentsOfDirectory(atPath: supportDirectory.path())
            .filter(Self.isRuntimeHelper)
            .sorted()

        let inputs = names.map { supportDirectory.appending(path: $0) }
        let output = context.pluginWorkDirectoryURL.appending(path: "RunnerSupportSources.swift")

        var swift = """
            // Generated by Plugins/EmbedRunnerSupport. Do not edit, and do not
            // commit — this file lives in the plugin work directory.
            //
            // Each entry is one file from Tools/runner-support/, verbatim. The
            // canonical file is the only copy; there is no second one to drift.

            let canonicalRuntimeHelperSources: [String: String] = [\n
            """
        for name in names {
            let contents = try String(contentsOf: supportDirectory.appending(path: name), encoding: .utf8)
            swift += "    \(Self.swiftLiteral(name)): \(Self.swiftLiteral(contents)),\n"
        }
        swift += "]\n"

        try swift.write(to: output, atomically: true, encoding: .utf8)

        // A prebuild command would re-read the files on every build; this is a
        // plain build command whose inputs are the canonical files, so SwiftPM
        // re-runs it only when one of them changes. The work is already done
        // above (the plugin runs at manifest time), so the command itself just
        // has to declare the dependency and leave the file in place.
        return [
            .buildCommand(
                displayName: "Embed \(names.count) runner-support file(s)",
                executable: URL(fileURLWithPath: "/usr/bin/env"),
                arguments: ["true"],
                inputFiles: inputs,
                outputFiles: [output])
        ]
    }

    /// A Swift string literal for arbitrary text.
    ///
    /// Single-line and fully escaped rather than a raw multiline literal. A
    /// multiline literal has two traps this avoids outright: its indentation is
    /// stripped relative to the closing delimiter, and its trailing newline is
    /// dropped — both of which would silently alter bytes that a student's test
    /// run depends on. Nobody reads this output, so legibility is worth nothing
    /// and exactness is worth everything.
    private static func swiftLiteral(_ text: String) -> String {
        var out = "\""
        for scalar in text.unicodeScalars {
            switch scalar {
            case "\\": out += "\\\\"
            case "\"": out += "\\\""
            case "\n": out += "\\n"
            case "\r": out += "\\r"
            case "\t": out += "\\t"
            case "\0": out += "\\0"
            default:
                // Other control characters would be legal in the file and
                // illegal (or invisible) in a literal.
                if scalar.value < 0x20 {
                    out += String(format: "\\u{%02x}", scalar.value)
                } else {
                    out.unicodeScalars.append(scalar)
                }
            }
        }
        return out + "\""
    }
}
