// Core/AssignmentLanguage.swift
//
// The programming language an assignment is authored + graded in, made
// first-class so every language-specific path (literal rendering, per-student
// expression evaluation, `_ck_inputs.*` value delivery, notebook substitution)
// dispatches on one resolved value instead of re-sniffing file extensions or
// notebook kernelspecs at each call site.

import Foundation

public enum AssignmentLanguage: String, Codable, Sendable, CaseIterable {
    case python
    case r

    /// Kernelspec `name` values (and `language_info.name`) that mark an R
    /// notebook. Single source of truth for the detection currently duplicated
    /// in the worker's `submissionIsRNotebook` and `extractNotebooksToCode`.
    public static let rKernelNames: Set<String> = ["ir", "r", "webr", "xr"]

    /// Resolve the language from the manifest and (optionally) the notebook
    /// kernel. Precedence:
    ///   1. any `.R`/`.r` graded test script → `.r` (the graded suite is the
    ///      strongest signal — it's what actually runs);
    ///   2. else an R notebook kernel (`kernelspec.name` in `rKernelNames`, or
    ///      `language_info.name == "r"`) → `.r`;
    ///   3. else `.python` — the default, so every existing assignment resolves
    ///      exactly as today and its generated bytes stay byte-for-byte identical.
    public static func resolve(
        manifest: TestProperties,
        notebookKernelName: String? = nil,
        notebookLanguageInfoName: String? = nil
    ) -> AssignmentLanguage {
        let hasRScript = manifest.testSuites.contains {
            URL(fileURLWithPath: $0.script).pathExtension.lowercased() == "r"
        }
        if hasRScript { return .r }
        if let kernel = notebookKernelName?.lowercased(), rKernelNames.contains(kernel) { return .r }
        if notebookLanguageInfoName?.lowercased() == "r" { return .r }
        return .python
    }
}
