// Core/AssignmentLanguage.swift
//
// The programming language an assignment is authored + graded in, made
// first-class so every language-specific path (literal rendering, per-student
// expression evaluation, `_ck_inputs.*` value delivery, notebook substitution)
// dispatches on one resolved value instead of re-sniffing file extensions or
// notebook kernelspecs at each call site.

import Foundation

public enum AssignmentLanguage: String, Codable, Sendable, CaseIterable {
    case python
    case r

    /// What an assignment resolves to when nothing about it says otherwise.
    ///
    /// Named rather than written as `.python` at the comparison sites, because
    /// those sites are asking "did resolution fall back?" and not "is this
    /// Python?". The two questions have the same answer today and would diverge
    /// the moment a third language existed: `manifestOnly == .python` would
    /// stop consulting the notebook kernelspec for a Julia assignment that had
    /// resolved positively, which is the opposite of what that guard wants.
    public static let `default`: AssignmentLanguage = .python

    /// Kernelspec `name` values (and `language_info.name`) that mark an R
    /// notebook. The single source of truth for the sniff: every Swift consumer
    /// reads it through `isRNotebookMetadata(_:)` rather than re-listing the
    /// aliases, so teaching Chickadee a new R kernel is one edit here.
    ///
    /// The browser runner cannot import Swift, so `Public/browser-runner.js`
    /// carries a generated copy in `R_KERNEL_NAMES`, written into a fenced
    /// block by `scripts/generate-js-constants.sh` from this declaration.
    /// After editing this set, run that script; the CI format-lint job fails
    /// while the generated copy is stale.
    public static let rKernelNames: Set<String> = ["ir", "r", "webr", "xr"]

    /// Graded-script filename extensions (lowercased) that mark this language.
    /// The single source of truth for the "`.R` script → R assignment" sniff,
    /// consolidated from the resolution, worker-routing, and raw-script
    /// inlining sites that each hand-inlined it
    /// (docs/language-handling-review.md §4 — the same shape `rKernelNames`
    /// was in before #1230).
    public var scriptExtensions: Set<String> {
        switch self {
        case .python: return ["py"]
        case .r: return ["r"]
        }
    }

    /// The language a graded-script filename extension implies, or nil for an
    /// extension that carries no language signal (`sh`, data files, …).
    /// Case-insensitive, so `.R` and `.r` both answer `.r`.
    public init?(scriptExtension: String) {
        let lowered = scriptExtension.lowercased()
        guard
            let match = AssignmentLanguage.allCases.first(where: {
                $0.scriptExtensions.contains(lowered)
            })
        else { return nil }
        self = match
    }

    /// Resolve the language from the manifest and (optionally) the notebook
    /// kernel. Precedence:
    ///   0. the manifest's recorded `language`, when it has one — an explicit
    ///      answer always beats sniffing, and it is what lets a suite made up
    ///      only of pattern families (no `.R` script to find) stay R;
    ///   1. any `.R`/`.r` graded test script → `.r` (the graded suite is the
    ///      strongest signal — it's what actually runs);
    ///   2. else an R notebook kernel (`kernelspec.name` in `rKernelNames`, or
    ///      `language_info.name == "r"`) → `.r`;
    ///   3. else `.python` — the default, so every existing assignment resolves
    ///      exactly as today and its generated bytes stay byte-for-byte identical.
    ///
    /// Deliberately not public (docs/language-handling-review.md §3): the
    /// defaulted parameters made `resolve(manifest: props)` an easy spelling
    /// that silently skips the notebook sniff — the bug class the
    /// `resolve(for:manifest:)` server wrapper exists to prevent. External
    /// callers state their notebook source explicitly: `resolve(manifest:notebookData:)`
    /// here, or the `APITestSetup` wrapper in `AssignmentLanguageResolution.swift`.
    static func resolve(
        manifest: TestProperties,
        notebookKernelName: String? = nil,
        notebookLanguageInfoName: String? = nil
    ) -> AssignmentLanguage {
        if let recorded = manifest.language { return recorded }
        let hasRScript = manifest.testSuites.contains {
            AssignmentLanguage(scriptExtension: URL(fileURLWithPath: $0.script).pathExtension) == .r
        }
        if hasRScript { return .r }
        if let kernel = notebookKernelName?.lowercased(), rKernelNames.contains(kernel) { return .r }
        if notebookLanguageInfoName?.lowercased() == "r" { return .r }
        return .python
    }
}

extension AssignmentLanguage {

    /// True when a notebook's `metadata` marks it as R: `kernelspec.name` is in
    /// `rKernelNames`, or `language_info.name` is `"r"`.
    ///
    /// The one implementation of that two-step sniff. `rederive`, the worker's
    /// submission routing (`submissionIsRNotebook`) and its notebook→source
    /// extraction (`extractNotebooksToCode`) all call through here, so the
    /// alias list lives in exactly one place.
    public static func isRNotebookMetadata(_ metadata: [String: Any]) -> Bool {
        if let kernel = (metadata["kernelspec"] as? [String: Any])?["name"] as? String,
            rKernelNames.contains(kernel.lowercased())
        {
            return true
        }
        return ((metadata["language_info"] as? [String: Any])?["name"] as? String)?
            .lowercased() == "r"
    }

    /// `isRNotebookMetadata(_:)` for a parsed notebook object. A notebook with
    /// no `metadata` has nothing to sniff and is not R — matching what every
    /// caller already did on a missing/unparseable metadata dictionary.
    public static func isRNotebook(_ notebook: [String: Any]) -> Bool {
        guard let metadata = notebook["metadata"] as? [String: Any] else { return false }
        return isRNotebookMetadata(metadata)
    }

    /// Resolve including the assignment's starter notebook, read straight from
    /// `.ipynb` bytes.
    ///
    /// This is the only signal a *brand-new* notebook assignment has. Its suite
    /// is still empty and nothing has recorded a language yet, so
    /// `resolve(manifest:)` alone answers `.python` — which meant an
    /// instructor's first R `=` expression was evaluated by `python3` and
    /// rejected with a Python `SyntaxError`, before any `.R` script existed to
    /// give the game away.
    ///
    /// Falls back to the manifest-only resolution when the notebook is absent
    /// or unparseable, so nothing regresses for assignments without one.
    /// `notebookData` is an autoclosure because only step 2 of the precedence
    /// needs it: a recorded language or an `.R` script in the suite both
    /// outrank the kernelspec, so callers on hot paths (the worker job payload,
    /// every suite save) don't pay to read the notebook off disk to be told
    /// something the manifest already knew.
    public static func resolve(
        manifest: TestProperties,
        notebookData: @autoclosure () -> Data?
    ) -> AssignmentLanguage {
        let manifestOnly = resolve(manifest: manifest)
        // `== .default`, not `== .python`: the question is whether resolution
        // fell back, so that the kernelspec is only consulted when the manifest
        // said nothing. See the `default` declaration.
        guard manifest.language == nil, manifestOnly == .default else { return manifestOnly }
        guard let data = notebookData(),
            let notebook = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
            let metadata = notebook["metadata"] as? [String: Any]
        else {
            return manifestOnly
        }
        return resolve(
            manifest: manifest,
            notebookKernelName: (metadata["kernelspec"] as? [String: Any])?["name"] as? String,
            notebookLanguageInfoName: (metadata["language_info"] as? [String: Any])?["name"]
                as? String
        )
    }

    /// Re-derive the language from scratch, **ignoring any recorded
    /// `manifest.language`**.
    ///
    /// `resolve` treats a recorded language as an authoritative answer (step 0),
    /// which is what a stable render needs — but it also makes the recorded value
    /// a one-way door: a Python assignment cloned and converted to R keeps
    /// rendering `.py` forever, because the sticky `.python` outranks the new R
    /// notebook. When the starter notebook is *replaced* the recorded value is a
    /// stale memo, not a declaration, so re-derivation must skip it. Precedence
    /// is otherwise identical to `resolve`: an `.R`/`.r` graded script wins, else
    /// an R notebook kernel (`kernelspec.name` in `rKernelNames`, or
    /// `language_info.name == "r"`), else `.python`.
    public static func rederive(
        manifest: TestProperties,
        notebookData: @autoclosure () -> Data?
    ) -> AssignmentLanguage {
        let hasRScript = manifest.testSuites.contains {
            AssignmentLanguage(scriptExtension: URL(fileURLWithPath: $0.script).pathExtension) == .r
        }
        if hasRScript { return .r }
        guard let data = notebookData(),
            let notebook = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any],
            let metadata = notebook["metadata"] as? [String: Any]
        else {
            return .python
        }
        return isRNotebookMetadata(metadata) ? .r : .python
    }
}

// MARK: - Per-language rendering / delivery strategy
//
// A closed 2-case enum owns its own language-specific behavior (cleaner than a
// protocol + 2 conformances). Every site that used to hardcode Python — literal
// rendering, the `_ck_inputs.*` file, the expression driver — dispatches here so
// adding a third language later is one `case`.

extension AssignmentLanguage {

    /// Render a JSON value as a source literal in this language.
    public func literal(_ value: JSONValue) -> String {
        switch self {
        case .python: return value.pythonLiteral
        case .r: return value.rLiteral
        }
    }

    /// Filename of the per-student grading-inputs file the worker materializes.
    public var inputsFileName: String {
        switch self {
        case .python: return "_ck_inputs.py"
        case .r: return "_ck_inputs.R"
        }
    }

    /// Extension for scripts Chickadee generates (pattern-family cases,
    /// notebook checks). `.py` for Python — unchanged, so every existing
    /// generated filename, `spec_hash` and `TestSetupCache` key is stable.
    public var generatedScriptExtension: String {
        switch self {
        case .python: return "py"
        case .r: return "R"
        }
    }

    /// Body of the per-student grading-inputs file. `values` maps each input
    /// name to its already-rendered literal *in this language* (Python literal
    /// for `.python`, R literal for `.r`). Keys are emitted in sorted order for
    /// deterministic output.
    ///
    /// The `.python` form is byte-for-byte identical to the historical
    /// `_ck_inputs.py` writer, so existing assignments are unchanged. The `.r`
    /// form binds `.ck_inputs` (R forbids a leading-underscore identifier, so the
    /// variable can't be `_ck`) and omits the trailing comma R's `list()` rejects.
    public func renderInputsFile(_ values: [String: String]) -> String {
        let header = "# Auto-generated per-student grading inputs (issue #461). Do not edit."
        let keys = values.keys.sorted()
        switch self {
        case .python:
            var lines = [header, "_ck = {"]
            for key in keys {
                lines.append("    \(JSONValue.string(key).pythonLiteral): \(values[key] ?? "None"),")
            }
            lines.append("}")
            return lines.joined(separator: "\n") + "\n"
        case .r:
            guard !keys.isEmpty else { return "\(header)\n.ck_inputs <- list()\n" }
            let assignments = keys.map { "    `\($0)` = \(values[$0] ?? "NULL")" }
            return "\(header)\n.ck_inputs <- list(\n"
                + assignments.joined(separator: ",\n")
                + "\n)\n"
        }
    }

    // MARK: - Language-specific facts that were boolean tests
    //
    // Each of these replaced an `if language == .python` / `== .r` at its call
    // site. The equality form compiles fine when a third case is added and
    // silently routes it down whichever branch it happens to fall — Python bytes
    // for a Julia assignment, R's error wording for a Julia ImportError. An
    // exhaustive switch here turns each of those into a compile error naming the
    // decision that has to be made. See docs/language-handling-review.md §4.

    /// The env file a maintainer edits to add a package to this language's
    /// browser-grading kernel, named in the authoring rejection message.
    public var kernelEnvironmentFileName: String {
        switch self {
        case .python: return "environment-python.yml"
        case .r: return "environment-r.yml"
        }
    }

    /// How a missing dependency presents to a student at grade time, phrased for
    /// the same rejection message.
    public var missingDependencyFailureDescription: String {
        switch self {
        case .python: return "an ImportError"
        case .r: return "an error from library()"
        }
    }

    /// Modules the RUNNER injects into the grading workspace, which are therefore
    /// importable even though no kernel package ships them.
    ///
    /// Empty for R by fact, not by omission: R reaches its runtime with
    /// `source("test_runtime.R")`, which is a file read rather than a package
    /// load, so nothing here is `library()`-able. A third language must answer
    /// this rather than inherit R's silence.
    public var runnerProvidedModules: Set<String> {
        switch self {
        case .python: return ["test_runtime", "sitecustomize", "_ck_inputs"]
        case .r: return []
        }
    }

    /// Prefixes of extracted-submission modules. The concrete name depends on
    /// what a student uploads and is unknowable while authoring, so the guard
    /// matches on prefix. Empty for R for the same reason as above.
    public var studentModulePrefixes: [String] {
        switch self {
        case .python: return ["student", "_ck_"]
        case .r: return []
        }
    }

    /// Environment variable that puts the assignment's support files on this
    /// language's module search path when the personalization driver runs.
    /// `nil` where the language has no such mechanism.
    public var supportFilesPathEnvironmentVariable: String? {
        switch self {
        case .python: return "PYTHONPATH"
        // Rscript resolves `source()` relative to the working directory the
        // driver already sets, so there is nothing to put on a path.
        case .r: return nil
        }
    }
}
