#!/bin/sh
# certbot pre-hook: /etc/letsencrypt/renewal-hooks/pre/open-port-80.sh
#
# The host firewall is generated by IST's SaltStack (`/etc/iptables/rules.v4`,
# "DO NOT EDIT"). Its policy opens 443 to the world (`rule.https_world`) but 80
# only to campus (`rule.http_campus`). Let's Encrypt validates HTTP-01 from off
# campus on port 80, so every renewal timed out, and nothing said so until the
# certificate expired on 2026-09-22.
#
# certbot runs this hook only when a certificate is due, immediately before the
# attempt; close-port-80.sh removes the rule immediately after. Port 80 is open
# to the world for the seconds a renewal takes and campus-only otherwise, which
# keeps IST's policy in force the rest of the time.
#
# One inserted rule, never a restore: `iptables-restore` and
# `netfilter-persistent` replace whole tables and delete Docker's chains (see
# docker-restart-after-netfilter.conf). The rule is tagged, so the post-hook
# removes exactly this rule and nothing else. The check makes a second run a
# no-op. IPv4 only: the host has no AAAA record.
#
# Install: see "Certificate renewal" in deploy/README.md.
set -eu

if ! iptables -C INPUT -p tcp --dport 80 -m comment --comment chickadee-acme -j ACCEPT 2>/dev/null; then
  iptables -I INPUT 1 -p tcp --dport 80 -m comment --comment chickadee-acme -j ACCEPT
fi
