#!/bin/sh
# Generated by Chickadee — do not edit. This wrapper runs the
# submission as a whole program (java in source-file mode) with the
# case's standard input, and grades what it printed under the
# ordinary shell-script contract.
student_file=""
if [ -f .chickadee_student_module ]; then
    student_file=$(cat .chickadee_student_module)
fi
if [ ! -f "$student_file" ]; then
    for candidate in *.java; do
        case "$candidate" in
            *test_*|_ck_inputs.java|CkProgram_*) ;;
            *) student_file="$candidate"; break ;;
        esac
    done
fi
if [ ! -f "$student_file" ]; then
    echo "No Java submission file was found to run." 1>&2
    exit 2
fi
printf '%s' '3
4
' > '.ck_stdin_fam_01'
cat > 'CkProgram_CkTest_fam_01.java' <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01'.
// Edit the family, not this file. spec_hash: 3d16a9454e8a2068
public class CkProgram_CkTest_fam_01 {
    static String ckNormalize(String text) {
        String[] lines = text.replace("\r\n", "\n").split("\n", -1);
        java.util.List<String> kept = new java.util.ArrayList<>();
        for (String line : lines) kept.add(line.replaceAll("\\s+$", ""));
        while (!kept.isEmpty() && kept.get(kept.size() - 1).isEmpty()) kept.remove(kept.size() - 1);
        return String.join("\n", kept);
    }
    public static void main(String[] ckArgs) throws Exception {
        String stdin_text = "3\n4\n";
        String expected = "7";
        ProcessBuilder ckBuilder = new ProcessBuilder("java", ckArgs[0]);
        ckBuilder.redirectInput(new java.io.File(".ck_stdin_fam_01"));
        Process ckProcess = ckBuilder.start();
        byte[] ckOutBytes = ckProcess.getInputStream().readAllBytes();
        byte[] ckErrBytes = ckProcess.getErrorStream().readAllBytes();
        int ckCode = ckProcess.waitFor();
        String ckPrinted = new String(ckOutBytes, java.nio.charset.StandardCharsets.UTF_8);
        String ckStderr = new String(ckErrBytes, java.nio.charset.StandardCharsets.UTF_8);
        if (ckCode != 0) {
            ck.failed("unexpected exception\n"
                + "  input:    " + ck.format(stdin_text) + "\n"
                + "  got:      " + ck.format(ckNormalize(ckPrinted)) + "\n"
                + "  error:    the program exited with status " + ckCode
                + (ckStderr.isEmpty() ? "" : ": " + ckNormalize(ckStderr)));
        }
        boolean ckOk = ckNormalize(ckPrinted).equals(ckNormalize(expected));
        if (!ckOk) {
            ck.failed("wrong output\n"
                + "  input:    " + ck.format(stdin_text) + "\n"
                + "  expected: " + ck.format(expected) + "\n"
                + "  got:      " + ck.format(ckNormalize(ckPrinted)));
        }
        ck.passed("Printed the expected output");
    }
}
CHICKADEE_GENERATED_SOURCE
if ! javac -encoding UTF-8 -cp . -d . CkProgram_CkTest_fam_01.java test_runtime.java 2>.ck_build_log; then
    cat .ck_build_log 1>&2
    exit 2
fi
ck_out=$(java -ea -cp . CkProgram_CkTest_fam_01 "$student_file")
ck_rc=$?
if ! printf '%s\n' "$ck_out" | grep -q '^CK_SENTINEL$'; then
    echo "The test did not run to completion." 1>&2
    exit 2
fi
printf '%s\n' "$ck_out" | grep -v '^CK_SENTINEL$'
exit $ck_rc
