#!/bin/sh
# Generated by Chickadee — do not edit. The C++ source below is the
# test; this wrapper locates the submission, compiles one translation
# unit with the injected runtime, and runs it under the ordinary
# shell-script contract.
student_file=""
if [ -f .chickadee_student_module ]; then
    student_file=$(cat .chickadee_student_module)
fi
if [ ! -f "$student_file" ]; then
    for candidate in *.cpp; do
        case "$candidate" in
            .ck_*|*test_*) ;;
            *) student_file="$candidate"; break ;;
        esac
    done
fi
if [ ! -f "$student_file" ]; then
    echo "No C++ submission file was found to grade." 1>&2
    exit 2
fi
cp "$student_file" .ck_solution.cpp
cat > .ck_src_fam_01.cpp <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (e).
// Edit the family, not this file. spec_hash: af181e8a5562a736
#include "test_runtime.hpp"
#define main ck_student_main
#include ".ck_solution.cpp"
#undef main
int main() {
    auto x = -1;
    std::string what;
    auto outcome = ck::expect_throw(
        [&] { (void)classify(x); }, "ValueError", what);
    if (outcome == ck::ThrowOutcome::returned) {
        ck::failed(std::string("no error raised\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  expected: an exception matching \"ValueError\"");
    }
    if (outcome == ck::ThrowOutcome::threwOther) {
        ck::failed(std::string("wrong error raised\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  expected: an exception matching \"ValueError\"\n"
            + "  got:      " + what);
    }
    ck::passed("Raised as expected: " + what);
}
CHICKADEE_GENERATED_SOURCE
g++ -std=c++20 -O0 .ck_src_fam_01.cpp -o .ck_bin_fam_01 1>&2 || exit 2
exec ./.ck_bin_fam_01
