#!/bin/sh
# Generated by Chickadee — do not edit. The Java source below is the
# test; this wrapper compiles it with the injected runtime and runs it
# under the ordinary shell-script contract. javac pulls the student's
# class and _ck_inputs.java in from the sourcepath on demand, so
# nothing here has to locate or copy the submission.
cat > 'CkTest_fam_01.java' <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (e).
// Edit the family, not this file. spec_hash: ebe51984e149506a
public class CkTest_fam_01 {
    public static void main(String[] ckArgs) throws Exception {
        var x = -1;
        String[] ckWhat = new String[1];
        int ckOutcome = ck.expectThrow(
            () -> { Solution.classify(x); return null; }, "ValueError", ckWhat);
        if (ckOutcome == ck.RETURNED) {
            ck.failed("no error raised\n"
                + "  input:    " + "x=" + ck.format(x) + "\n"
                + "  expected: an exception matching \"ValueError\"");
        }
        if (ckOutcome == ck.THREW_OTHER) {
            ck.failed("wrong error raised\n"
                + "  input:    " + "x=" + ck.format(x) + "\n"
                + "  expected: an exception matching \"ValueError\"\n"
                + "  got:      " + ckWhat[0]);
        }
        ck.passed("Raised as expected: " + ckWhat[0]);
    }
}
CHICKADEE_GENERATED_SOURCE
if ! javac -encoding UTF-8 -cp . -d . CkTest_fam_01.java test_runtime.java 2>.ck_build_log; then
    cat .ck_build_log 1>&2
    exit 2
fi
ck_out=$(java -cp . CkTest_fam_01)
ck_rc=$?
# The sentinel check. Without it, a student's own System.exit(0)
# anywhere in their code exits the JVM with status 0 and this case —
# every case — reads as a pass. Java's masking mechanism
# (SecurityManager) is deprecated for removal, so the test prints a line
# only it can print and the wrapper refuses a run that lacks it.
if ! printf '%s\n' "$ck_out" | grep -q '^CK_SENTINEL$'; then
    echo "The test did not run to completion. Does the submission call System.exit?" 1>&2
    exit 2
fi
printf '%s\n' "$ck_out" | grep -v '^CK_SENTINEL$'
exit $ck_rc
