#!/bin/sh
# Generated by Chickadee — do not edit. This wrapper compiles the
# submission as a whole program, runs it with the case's standard
# input, and grades what it printed under the ordinary shell-script
# contract.
student_file=""
if [ -f .chickadee_student_module ]; then
    student_file=$(cat .chickadee_student_module)
fi
if [ ! -f "$student_file" ]; then
    for candidate in *.cpp; do
        case "$candidate" in
            *test_*) ;;
            *) student_file="$candidate"; break ;;
        esac
    done
fi
if [ ! -f "$student_file" ]; then
    echo "No C++ submission file was found to run." 1>&2
    exit 2
fi
if ! g++ -std=c++20 -O0 "$student_file" -o '.ck_prog_fam_01' >.ck_build_log 2>&1; then
    cat .ck_build_log 1>&2
    printf '%s\n' '{"shortResult": "the submission does not compile"}'
    exit 1
fi
printf '%s' '3
4
' > '.ck_stdin_fam_01'
cat > '.ck_src_fam_01.cpp' <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01'.
// Edit the family, not this file. spec_hash: eb00ef813bc014b0
#include "test_runtime.hpp"
#include <regex>
#include <sys/wait.h>

static std::string ck_read_file(const char* path) {
    std::ifstream in(path, std::ios::binary);
    std::ostringstream ss;
    ss << in.rdbuf();
    return ss.str();
}
static bool ck_regex_any_line(const std::string& text, const std::string& pattern) {
    std::regex re(pattern, std::regex::ECMAScript);
    if (std::regex_search(text, re)) return true;
    std::istringstream in(text);
    for (std::string line; std::getline(in, line);) {
        if (std::regex_search(line, re)) return true;
    }
    return false;
}
static std::string ck_normalize(const std::string& text) {
    std::vector<std::string> lines;
    std::string current;
    for (char ch : text) {
        if (ch == '\n') { lines.push_back(current); current.clear(); }
        else if (ch != '\r') { current.push_back(ch); }
    }
    lines.push_back(current);
    for (auto& line : lines) {
        while (!line.empty() && std::isspace(static_cast<unsigned char>(line.back()))) line.pop_back();
    }
    while (!lines.empty() && lines.back().empty()) lines.pop_back();
    std::string out;
    for (std::size_t i = 0; i < lines.size(); ++i) {
        if (i) out.push_back('\n');
        out += lines[i];
    }
    return out;
}

int main() {
    std::string stdin_text = std::string("3\n4\n");
    std::string expected = std::string("7");
    int ck_status = std::system("./.ck_prog_fam_01 < .ck_stdin_fam_01 > .ck_out_fam_01 2> .ck_err_fam_01");
    std::string ck_printed = ck_read_file(".ck_out_fam_01");
    std::string ck_stderr = ck_read_file(".ck_err_fam_01");
    int ck_code = WIFEXITED(ck_status) ? WEXITSTATUS(ck_status) : -1;
    if (ck_code != 0) {
        ck::failed(std::string("unexpected exception\n")
            + "  input:    " + ck::format(stdin_text) + "\n"
            + "  got:      " + ck::format(ck_normalize(ck_printed)) + "\n"
            + "  error:    the program exited with status " + std::to_string(ck_code)
            + (ck_stderr.empty() ? std::string("") : ": " + ck_normalize(ck_stderr)));
    }
    bool ck_ok = ck_normalize(ck_printed) == ck_normalize(expected);
    if (!ck_ok) {
        ck::failed(std::string("wrong output\n")
            + "  input:    " + ck::format(stdin_text) + "\n"
            + "  expected: " + ck::format(expected) + "\n"
            + "  got:      " + ck::format(ck_normalize(ck_printed)));
    }
    ck::passed("Printed the expected output");
}
CHICKADEE_GENERATED_SOURCE
if ! g++ -std=c++20 -O0 '.ck_src_fam_01.cpp' -o '.ck_bin_fam_01' >.ck_build_log 2>&1; then
    cat .ck_build_log 1>&2
    exit 2
fi
ck_out=$('./.ck_bin_fam_01')
ck_rc=$?
if ! printf '%s\n' "$ck_out" | grep -q '^CK_SENTINEL$'; then
    echo "The test did not run to completion." 1>&2
    exit 2
fi
printf '%s\n' "$ck_out" | grep -v '^CK_SENTINEL$'
exit $ck_rc
