// Rebuilds data/first-names.txt and data/surnames.txt from the downloaded
// source files.  The sources, their licences and the fetch dates are in
// data/README.md; this script is only the derivation, so a reviewer can see
// exactly which rows became a flag.
//
//   node Tools/handle-review/build-names.mjs <ssa-csv> <ontario-female-csv> <ontario-male-csv> <census-xlsx>
//
// Nothing in CI runs it.  The committed .txt files are the input the review
// tool and the Swift tests read.

import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const [ssaPath, onFemalePath, onMalePath, censusPath] = process.argv.slice(2)
if (!censusPath) {
  console.error('usage: build-names.mjs <ssa-csv> <ontario-female-csv> <ontario-male-csv> <census-xlsx>')
  process.exit(2)
}

// The first year counted.  Students, their classmates and their parents were
// all born after it, so a name that was common only before it is not the one
// a classmate carries.
const firstYear = 1950
const titleCase = (s) => s.charAt(0).toUpperCase() + s.slice(1).toLowerCase()
const lines = (path) => readFileSync(path, 'utf8').replace(/^﻿/, '').split(/\r?\n/).slice(1)
  .filter(Boolean).map((l) => l.split(',').map((f) => f.replace(/^"|"$/g, '')))

const names = new Set()

// SSA: the file already holds the top 1,000 names per sex per year.
for (const [year, name] of lines(ssaPath)) {
  if (Number(year) >= firstYear) names.add(titleCase(name))
}

// Ontario: every name with five or more births in a year.  Keep the top 500 per
// sex per year.
for (const path of [onFemalePath, onMalePath]) {
  const byYear = new Map()
  for (const [year, name, count] of lines(path)) {
    if (Number(year) < firstYear) continue
    if (!byYear.has(year)) byYear.set(year, [])
    byYear.get(year).push([name, Number(count)])
  }
  for (const rows of byYear.values()) {
    rows.sort((a, b) => b[1] - a[1])
    for (const [name] of rows.slice(0, 500)) names.add(titleCase(name))
  }
}

// Census 2010: column A of the sheet, rank order, as shared-string indexes.
const strings = [...execFileSync('unzip', ['-p', censusPath, 'xl/sharedStrings.xml'], { encoding: 'utf8' })
  .matchAll(/<si>(?:<t[^>]*>([^<]*)<\/t>|[\s\S]*?)<\/si>/g)].map((m) => m[1] ?? '')
const sheet = execFileSync('unzip', ['-p', censusPath, 'xl/worksheets/sheet1.xml'], { encoding: 'utf8' })
const surnames = [...sheet.matchAll(/<c r="A(\d+)"[^>]*t="s"[^>]*><v>(\d+)<\/v><\/c>/g)]
  .map((m) => strings[Number(m[2])])
  .filter((s) => /^[A-Z]+$/.test(s))
  .slice(0, 1000)
  .map(titleCase)

const write = (file, header, words) =>
  writeFileSync(`${here}/data/${file}`, `${header}\n${[...new Set(words)].sort().join('\n')}\n`)
write('first-names.txt', '# Generated by build-names.mjs. See README.md for sources.', names)
write('surnames.txt', '# Generated by build-names.mjs. See README.md for sources.', surnames)
console.error(`first names: ${names.size}, surnames: ${surnames.length}`)
