#!/bin/sh
# Generated by Chickadee — do not edit. The Java source below is the
# test; this wrapper compiles it with the injected runtime and runs it
# under the ordinary shell-script contract. javac pulls the student's
# class and _ck_inputs.java in from the sourcepath on demand, so
# nothing here has to locate or copy the submission.
cat > CkTest_fam_01.java <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (d).
// Edit the family, not this file. spec_hash: 94c84c81b3acc3e3
public class CkTest_fam_01 {
    // Instructor's reference implementation, rendered verbatim.
    static int ck_ref_Solution_classify(double x) { return 1; }
    public static void main(String[] ckArgs) throws Exception {
        var x = 18.49;
        try {
            Object expected = null;
            try {
                expected = ck_ref_Solution_classify(x);
            } catch (Throwable ckRefE) {
                ck.errored("the reference implementation raised\n"
                    + "  input:    " + "x=" + ck.format(x) + "\n"
                    + "  error:    " + ckRefE);
            }
            var result = Solution.classify(x);
            if (!ck.equal(result, expected)) {
                ck.failed("wrong value\n"
                    + "  input:    " + "x=" + ck.format(x) + "\n"
                    + "  expected: " + ck.format(expected) + "\n"
                    + "  got:      " + ck.format(result));
            }
            ck.passed("Returned " + ck.format(result));
        } catch (Throwable ckE) {
            ck.failed("unexpected exception\n"
                + "  input:    " + "x=" + ck.format(x) + "\n"
                + "  error:    " + ckE);
        }
    }
}
CHICKADEE_GENERATED_SOURCE
if ! javac -encoding UTF-8 -cp . -d . CkTest_fam_01.java test_runtime.java 2>.ck_build_log; then
    cat .ck_build_log 1>&2
    exit 2
fi
ck_out=$(java -cp . CkTest_fam_01)
ck_rc=$?
# The sentinel check. Without it, a student's own System.exit(0)
# anywhere in their code exits the JVM with status 0 and this case —
# every case — reads as a pass. Java's masking mechanism
# (SecurityManager) is deprecated for removal, so the test prints a line
# only it can print and the wrapper refuses a run that lacks it.
if ! printf '%s\n' "$ck_out" | grep -q '^CK_SENTINEL$'; then
    echo "The test did not run to completion. Does the submission call System.exit?" 1>&2
    exit 2
fi
printf '%s\n' "$ck_out" | grep -v '^CK_SENTINEL$'
exit $ck_rc
