#!/bin/sh
# Generated by Chickadee — do not edit. The Java source below is the
# test; this wrapper compiles it with the injected runtime and runs it
# under the ordinary shell-script contract. javac pulls the student's
# class and _ck_inputs.java in from the sourcepath on demand, so
# nothing here has to locate or copy the submission.
cat > 'CkTest_fam_01.java' <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (v).
// Edit the family, not this file. spec_hash: e8ea0ebe1b20c72d
public class CkTest_fam_01 {
    public static void main(String[] ckArgs) throws Exception {
        var x = "total";
        var expected = 3;
        if (!ck.equal(Solution.classify, expected)) {
            ck.failed("Variable `Solution.classify` has the wrong value\n"
                + "  expected: " + ck.format(expected) + "\n"
                + "  got:      " + ck.format(Solution.classify));
        }
        ck.passed("Solution.classify is " + ck.format(Solution.classify));
    }
}
CHICKADEE_GENERATED_SOURCE
if ! javac -encoding UTF-8 -cp . -d . CkTest_fam_01.java test_runtime.java 2>.ck_build_log; then
    cat .ck_build_log 1>&2
    exit 2
fi
ck_out=$(java -cp . CkTest_fam_01)
ck_rc=$?
# The sentinel check. Without it, a student's own System.exit(0)
# anywhere in their code exits the JVM with status 0 and this case —
# every case — reads as a pass. Java's masking mechanism
# (SecurityManager) is deprecated for removal, so the test prints a line
# only it can print and the wrapper refuses a run that lacks it.
if ! printf '%s\n' "$ck_out" | grep -q '^CK_SENTINEL$'; then
    echo "The test did not run to completion. Does the submission call System.exit?" 1>&2
    exit 2
fi
printf '%s\n' "$ck_out" | grep -v '^CK_SENTINEL$'
exit $ck_rc
