// APIServer/Utilities/AuthoringLanguageFacts.swift
//
// The per-language facts the AUTHORING UI needs, computed server-side and
// seeded into the page as JSON.
//
// WHY THIS EXISTS. `Public/pattern-family-editor.js` contained the string
// "language" zero times. It validated names with `isValidPythonIdentifier`,
// parsed instructor input by Python rules (`True` / `False` / `None`),
// displayed stored values as Python reprs, and told an R author about "Python
// default" — for all six languages, with no gate and no signal. The server
// meanwhile rendered that same family correctly as R, Lua, Octave, C++ or
// Racket. So the generated test was right and every hint the instructor was
// given while authoring it was wrong.
//
// WHY THE LITERALS ARE COMPUTED, NOT TABULATED. The obvious shape is a table in
// JS listing each language's spelling of true/false/null, generated by
// `scripts/generate-js-constants.sh` like the kernel-alias sets. That would be a
// SECOND source of truth for something `JSONValue.literal(_:)` already answers,
// and the two could disagree — the instructor would be shown `TRUE` while the
// renderer emitted something else. These come from `language.literal(...)`
// itself, the same call that renders the real generated test, so a rendering
// change cannot leave the editor behind.
//
// Nothing here decides whether a FEATURE works. `functionScanning` and
// `expressionEvaluation` report what the surrounding system can actually do for
// this language today, so the UI can say so instead of silently producing
// nothing (the scan) or a Python answer for an R value (auto-compute).

import Core
import Foundation

/// What the browser-side authoring editors need to know about an assignment's
/// language.
///
/// Encoded into `#assignment-language-seed` on both authoring pages.
struct AuthoringLanguageFacts: Encodable, Equatable {

    /// The wire token (`r`, `lua`, …), or nil when the assignment declares no
    /// language — a plain `.sh` suite, where none of this applies.
    let name: String?

    /// How the language is written in prose the instructor reads.
    /// Nil-language assignments get nil, and the UI omits the language clause
    /// rather than inventing one.
    let displayName: String?

    /// This language's spelling of the three JSON scalars an instructor types
    /// by hand, straight from `JSONValue.literal(_:)`.
    ///
    /// Storage is language-neutral JSON; only ENTRY and DISPLAY are per
    /// language. So these are what the editor should accept in a value box and
    /// what it should echo back — `TRUE` on an R lab, `true` on Lua, `#t` on
    /// Racket — instead of Python's `True` everywhere.
    let trueLiteral: String?
    let falseLiteral: String?
    let nullLiteral: String?

    /// Whether scanning a solution notebook for function definitions works for
    /// this language.
    ///
    /// False everywhere but Python: `NotebookFunctionScanner` matches lines
    /// beginning `def `, which no R, Lua, Octave or Racket source produces. The
    /// scan does not fail on those languages — it returns nothing, and the
    /// instructor reads "No functions found." with no way to tell that from an
    /// empty solution. Reporting the capability lets the UI say which it is.
    let functionScanning: Bool

    /// Whether the editor can compute a case's expected value by running the
    /// solution in the browser.
    ///
    /// The evaluator is `/python-eval-worker.js`, a Python kernel, so for any
    /// other language it does not merely fail — it would compute a PYTHON
    /// answer for a value that will be compared against an R, Lua, Octave or
    /// Racket result. Wrong and confident is worse than absent, so the UI hides
    /// the control rather than offering it.
    let expressionEvaluation: Bool

    /// Facts for `language`, or the language-less answer when it is nil.
    init(_ language: AssignmentLanguage?) {
        guard let language else {
            self.name = nil
            self.displayName = nil
            self.trueLiteral = nil
            self.falseLiteral = nil
            self.nullLiteral = nil
            self.functionScanning = false
            self.expressionEvaluation = false
            return
        }
        self.name = language.rawValue
        self.displayName = language.displayName
        self.trueLiteral = language.literal(.bool(true))
        self.falseLiteral = language.literal(.bool(false))
        // A language that has no null value gets NO null token. C++ is the one:
        // `literal(.null)` there is the poison identifier its renderer emits so
        // that a leak becomes a compile error
        // (`CK_UNRENDERABLE_NULL_HAS_NO_CPP_VALUE`), and offering *that* as
        // something an instructor may type would be absurd. A C++ family cannot
        // carry a null anyway — `cppRenderabilityIssue` refuses it at save, and
        // this is the same refusal moved one step earlier, into the box.
        switch language {
        case .python, .r, .lua, .octave, .racket:
            self.nullLiteral = language.literal(.null)
        case .cpp:
            self.nullLiteral = nil
        }
        // DERIVED, not restated. These began as two hand-written bools here so
        // that scanning and evaluation had somewhere to be answered rather than
        // silently inherited — which was right at the time and became the same
        // bug one level up the moment the real answers existed elsewhere. Two
        // places to answer one question is exactly what this whole pass has
        // been removing.
        //
        // `notebookFunctionScanSupport` owns the first (its switch is the one a
        // seventh language must satisfy), and `PersonalizationEvaluator` owns
        // the second — it already spawns a per-language driver for all six, so
        // evaluation is available wherever a driver is.
        self.functionScanning = notebookFunctionScanSupport(for: language).isSupported
        self.expressionEvaluation = PersonalizationEvaluator.supportsEvaluation(language)
    }
}

/// `AuthoringLanguageFacts` as the JSON the page seeds. Mirrors
/// `notebookCheckFormSchemaJSON()`.
func authoringLanguageFactsJSON(_ language: AssignmentLanguage?) -> String {
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.sortedKeys]
    guard let data = try? encoder.encode(AuthoringLanguageFacts(language)),
        let json = String(data: data, encoding: .utf8)
    else { return "{}" }
    return json
}
