// APIServer/Utilities/GeneratedMessageVocabulary.swift
//
// The student-facing failure-message vocabulary, owned in one place instead of
// hand-retyped in every renderer.
//
// WHY THIS EXISTS. `"  expected: "` and `"  got:      "` were each hand-written
// in FOURTEEN files — both pattern-family renderers, both notebook-check
// renderers, both languages, plus the hand-authored templates — with nothing
// tying them together. A reworded Python failure silently diverged from the R
// one, and a student on an R lab read different prose than a student on a
// Python lab for the same mistake. `studentFacingWordingIsSharedAcrossLanguages`
// in LanguageConformanceMatrixTests pins that property from the outside; this
// is the thing that makes it true by construction rather than by vigilance.
//
// WHY IT IS AN ALIGNMENT GROUP AND NOT A FLAT LIST OF CONSTANTS. The padding is
// not arbitrary and it is not global: within one message every label is padded
// to one column, so the values line up when a student reads the failure in a
// terminal. The width therefore depends on the *longest label in that message*,
// which is why `data_frame_columns` renders `"  got:               "` (its
// message also carries `expected (subset):`) while everything else renders
// `"  got:      "`. Encoding that as a computed group means a new field, kind,
// or language gets alignment for free and CANNOT mis-pad it — the failure mode a
// flat constant list would have re-introduced the first time someone added a
// label longer than `expected:`.
//
// The generated bytes are pinned by `Tests/Fixtures/generated-source` goldens
// (and through them by `spec_hash` and the `TestSetupCache` key), so every
// group here reproduces its existing padding byte-for-byte.

import Foundation

/// A failure message's field labels, padded to a common column.
///
/// Construct with the label names a single message uses — without the colon —
/// and read them back through `label(_:)`. The column is `max(name) + ": "`,
/// indented two spaces, which is the rule every existing message already
/// followed.
struct MessageFields {
    /// Label names in the group, longest-first resolution handled by `width`.
    private let width: Int

    init(_ names: [String]) {
        // +1 for the colon the label carries, +1 for the single space that
        // separates the widest label from its value.
        width = (names.map(\.count).max() ?? 0) + 2
    }

    /// The rendered label, e.g. `"  expected: "` — two spaces, the name, a
    /// colon, and enough padding to reach the group's column.
    func label(_ name: String) -> String {
        let withColon = name + ":"
        let padding = String(repeating: " ", count: max(0, width - withColon.count))
        return "  " + withColon + padding
    }
}

/// The vocabulary itself: the phrases and label groups generated scripts are
/// built from, in every language.
///
/// Names are deliberately short — these are interpolated into Swift multi-line
/// templates that already carry the target language's own syntax, and a long
/// name makes the generated source harder to read in the template.
enum GeneratedMessage {

    // MARK: - Field labels

    /// The default group, used by nearly every generated failure. `expected` is
    /// the longest label in it, which is what puts the column at 12.
    static let standard = MessageFields([
        "input", "expected", "got", "error", "source", "delta", "hint", "row",
        "missing", "budget", "took", "raised", "position", "searched", "content",
    ])

    static let input = standard.label("input")
    static let expected = standard.label("expected")
    static let got = standard.label("got")
    static let error = standard.label("error")
    static let source = standard.label("source")
    static let delta = standard.label("delta")
    static let hint = standard.label("hint")
    static let row = standard.label("row")
    static let missing = standard.label("missing")
    static let budget = standard.label("budget")
    static let took = standard.label("took")
    static let position = standard.label("position")
    static let searched = standard.label("searched")

    /// `.performanceThreshold` in Python names its fields `threshold` and
    /// `elapsed`, which are longer than `expected`, so that message sits on its
    /// own wider column.
    ///
    /// Its `input:` line does NOT join this group — it comes from the shared
    /// call-context helper and stays on the standard column, leaving it one
    /// space short of the rest. That misalignment is pre-existing and load-
    /// bearing: the bytes feed `spec_hash`, so correcting it would rewrite every
    /// existing assignment's manifest. R renders the same kind entirely on the
    /// standard column (`budget:` / `took:`), which is why only Python needs
    /// this group at all.
    static let performance = MessageFields(["threshold", "elapsed", "error"])

    static let threshold = performance.label("threshold")
    static let elapsed = performance.label("elapsed")
    static let performanceError = performance.label("error")

    /// `data_frame_columns` in `.superset` mode: the message says
    /// `expected (subset):`, the longest label anywhere in the vocabulary.
    static let subsetColumns = MessageFields(["expected (subset)", "got", "missing"])

    static let expectedSubset = subsetColumns.label("expected (subset)")
    static let gotSubset = subsetColumns.label("got")
    static let missingSubset = subsetColumns.label("missing")

    /// The "not a DataFrame" guard, whose `expected columns:` label sets a
    /// column of its own.
    static let dataFrameColumns = MessageFields(["expected columns", "got"])

    static let expectedColumns = dataFrameColumns.label("expected columns")
    static let gotColumns = dataFrameColumns.label("got")

    /// `figure_count`, whose `expected at least:` label likewise widens it.
    static let atLeast = MessageFields(["expected at least", "got"])

    static let expectedAtLeast = atLeast.label("expected at least")
    static let gotAtLeast = atLeast.label("got")

    // MARK: - Shared phrases
    //
    // The first line of a failure message — what went wrong, before the fields
    // that say how. Shared across languages so the same mistake reads the same
    // way whichever language the assignment is in.

    static let unexpectedException = "unexpected exception"
    static let wrongValue = "wrong value"
    static let wrongReturnType = "wrong return type"
    static let wrongOutput = "wrong output"
    static let outsideTolerance = "value outside tolerance"
    static let returned = "Returned "

    /// `.differential`, when the INSTRUCTOR's reference implementation raises.
    ///
    /// Deliberately not phrased as a student failure, and reported through
    /// `errored` rather than `failed`: a student cannot make the reference
    /// raise except through inputs the instructor chose, so this outcome is a
    /// broken test, and a student reading "your function is wrong" would be
    /// debugging the wrong code.
    static let referenceFailed = "the reference implementation raised"

    /// `.unorderedEquality`'s mismatch line, which is one of the two places the
    /// languages genuinely say different things today: Python appends
    /// "(order doesn't matter)" and R does not.
    ///
    /// Named in both spellings rather than unified, because unifying them means
    /// changing generated bytes — a `spec_hash` rewrite of every existing
    /// assignment, which is a product decision and not a refactor. Naming them
    /// at least makes the divergence visible from one place; the other is
    /// `.performanceThreshold`, whose Python field labels (`threshold:` /
    /// `elapsed:`) and R ones (`budget:` / `took:`) differ likewise.
    static let wrongElements = "wrong elements"
    static let wrongElementsUnordered = "wrong elements (order doesn't matter)"
}
