// APIServer/Utilities/NotebookCheckRendererR+Code.swift
//
// The R half of the code-shape notebook checks: `.variableExists`,
// `.functionExists`, `.numericArrayClose` and `.figureCount`.
//
// Same separation as the data-frame half (NotebookCheckRendererR.swift):
// Python's generated bytes feed `spec_hash` and `TestSetupCache` keys and must
// never move, so R is written alongside rather than as branches inside the
// Python renderers.
//
// Two places where the honest R answer differs from a transliteration of the
// Python one:
//
//   * Python needs `test_runtime.student_main_state()` to see a variable that
//     only exists after top-level statements ran. R has no import/exec split —
//     `chickadee_load_student()` evaluates the submission expression by
//     expression — so the variable is simply there, and `.variableExists` and
//     `.numericArrayClose` read it directly.
//   * Python counts figures by monkeypatching `plt.show`. R has a documented
//     hook for exactly this: `plot.new` fires once per *high-level* plot
//     (`hist`, `plot`, `barplot`), and never for a low-level addition like
//     `lines()`. `grid.newpage` is hooked alongside it so lattice/ggplot2
//     count too if a course installs them.

import Core
import Foundation

// MARK: - .variableExists

func renderRVariableExists(_ check: NotebookCheck, specHash: String) -> String {
    let variable = check.variable ?? "variable"
    let typeName = check.expectedType.flatMap { $0.isEmpty ? nil : $0 }
    let expectation =
        typeName.map { "a variable named `\(variable)` holding a \($0)" }
        ?? "a variable named `\(variable)`"

    let typeCheck: String
    let passMessage: String
    if let typeName {
        // Type-name → predicate mapping is shared with the pattern-family
        // `.returnTypeCheck` renderer, so "DataFrame" means the same thing in
        // both and a family converted from Python keeps working.
        let predicate = rTypeCheckExpression(typeName: typeName, valueExpr: "actual")
        typeCheck = """
            expected_type_name <- \(JSONValue.string(typeName).rLiteral)
            if (!isTRUE(\(predicate))) {
                failed(paste0(
                    "Variable `", variable_name, "` has the wrong type.\\n",
                    "\(GeneratedMessage.expected)", expected_type_name, "\\n",
                    "\(GeneratedMessage.got)", class(actual)[[1L]]))
            }
            """
        passMessage =
            "paste0(\"`\", variable_name, \"` is defined and is a \", expected_type_name)"
    } else {
        typeCheck = "# (no type check; existence only)"
        passMessage = "paste0(\"`\", variable_name, \"` is defined\")"
    }

    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "variable_exists"))

        \(rFetchVariable(variable, expectation: expectation))

        \(typeCheck)

        passed(\(passMessage))
        """
}

// MARK: - .functionExists

func renderRFunctionExists(_ check: NotebookCheck, specHash: String) -> String {
    let name = check.variable ?? "function"

    let arityCheck: String
    if let arity = check.expectedArity {
        arityCheck = """
            # Count positional formals the way `formals()` reports them: an
            # argument with no default is stored as the empty symbol.  `...`
            # is excluded from the count and treated as "accepts more", so a
            # student who writes `f(x, ...)` still satisfies an arity of 3.
            # A primitive (a shadowed builtin) has no formals of its own —
            # `args()` gives it the documented signature instead.
            fmls <- if (is.primitive(fn)) formals(args(fn)) else formals(fn)
            if (is.null(fmls)) fmls <- pairlist()
            accepts_more <- "..." %in% names(fmls)
            positional <- fmls[names(fmls) != "..."]
            required <- sum(vapply(positional,
                                   function(d) is.symbol(d) && !nzchar(as.character(d)),
                                   logical(1)))
            total <- length(positional)
            expected_arity <- \(arity)

            if (accepts_more) {
                if (expected_arity < required) {
                    failed(paste0(
                        "`", fn_name, "` requires at least ", required,
                        " argument(s) but the test expected it to take ", expected_arity, "."))
                }
            } else if (expected_arity < required || expected_arity > total) {
                failed(paste0(
                    "`", fn_name, "` should take ", expected_arity, " argument(s), but it takes ",
                    if (required == total) as.character(total) else paste0(required, "-", total), "."))
            }
            """
    } else {
        arityCheck = "# (no arity check; existence + callability only)"
    }

    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "function_exists"))

        fn_name <- \(JSONValue.string(name).rLiteral)

        .ck_missing <- structure(list(), class = "ck_missing")
        fn <- tryCatch(get(fn_name, envir = student, inherits = FALSE),
                       error = function(e) .ck_missing)
        if (inherits(fn, "ck_missing")) {
            failed(paste0(
                "`", fn_name, "` is not defined in the student notebook.\\n",
                "\(GeneratedMessage.expected)a function named `", fn_name, "`"))
        }
        if (!is.function(fn)) {
            failed(paste0(
                "`", fn_name, "` is defined but is not a function.\\n",
                "  got: ", class(fn)[[1L]]))
        }

        \(arityCheck)

        passed(paste0("`", fn_name, "` is defined and callable"))
        """
}

// MARK: - .numericArrayClose

func renderRNumericArrayClose(_ check: NotebookCheck, specHash: String) -> String {
    let variable = check.variable ?? "array"
    let expected = check.expectedArray ?? []
    // numpy's `assert_allclose` defaults, so a check authored against the
    // Python renderer keeps the same tolerance when the course moves to R.
    let rtol = check.rtol ?? 1e-7
    let atol = check.atol ?? 0.0
    let expectedLiteral = "c(" + expected.map(rNumericLiteral).joined(separator: ", ") + ")"

    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "numeric_array_close"))

        \(rFetchVariable(variable, expectation: "a numeric vector of length \(expected.count)"))
        expected <- \(expected.isEmpty ? "numeric(0)" : expectedLiteral)
        rtol <- \(rtol)
        atol <- \(atol)

        actual_num <- suppressWarnings(as.numeric(actual))
        if (length(actual_num) > 0L && all(is.na(actual_num)) && !all(is.na(actual))) {
            failed(paste0(
                "Variable `", variable_name, "` could not be read as a numeric vector.\\n",
                "  got: ", class(actual)[[1L]]))
        }

        if (length(actual_num) != length(expected)) {
            failed(paste0(
                "Variable `", variable_name, "` has the wrong length.\\n",
                "\(GeneratedMessage.expected)", length(expected), " values\\n",
                "\(GeneratedMessage.got)", length(actual_num), " values"))
        }

        # Mirrors numpy's allclose, including its equal_nan default: two NaNs
        # agree, and two infinities of the same sign agree.  Non-finite
        # positions are settled by those two rules alone and never by the
        # tolerance — `rtol * Inf` is `Inf`, which would otherwise make every
        # infinity match every other one.
        both_nan <- is.nan(actual_num) & is.nan(expected)
        both_inf <- is.infinite(actual_num) & is.infinite(expected) &
            (sign(actual_num) == sign(expected))
        both_finite <- is.finite(actual_num) & is.finite(expected)
        delta <- abs(actual_num - expected)
        allowed <- atol + rtol * abs(expected)
        ok <- both_nan | both_inf | (both_finite & delta <= allowed)
        bad <- which(!ok)

        if (length(bad) > 0L) {
            i <- bad[[1L]]
            failed(paste0(
                "Variable `", variable_name, "` is not close enough to expected.\\n",
                "  position: ", i, "\\n",
                "\(GeneratedMessage.expected)", chickadee_format(expected[[i]]), "\\n",
                "\(GeneratedMessage.got)", chickadee_format(actual_num[[i]]), "\\n",
                "  tolerance: atol=", atol, " rtol=", rtol))
        }

        passed(paste0("`", variable_name, "` is close to expected (", length(expected), " values)"))
        """
}

/// Renders a `Double` as an R literal that survives into a numeric vector.
/// R spells the non-finite values `NaN` / `Inf` / `-Inf`; unlike Python they
/// are language keywords, not constructor calls.
func rNumericLiteral(_ value: Double) -> String {
    if value.isNaN { return "NaN" }
    if value.isInfinite { return value > 0 ? "Inf" : "-Inf" }
    return "\(value)"
}

// MARK: - .figureCount

func renderRFigureCount(_ check: NotebookCheck, specHash: String) -> String {
    let minFigures = check.minFigures ?? 1
    let label = check.name ?? notebookCheckKindHandler(for: check.kind).defaultLabel(check)

    // Deliberately not built on `rCheckPreamble`: the hooks have to be armed
    // *before* the submission is evaluated, so the `chickadee_load_student()`
    // call moves below them.
    return """
        # Test: \(rCheckComment(label))
        # Generated from notebook check "\(rCheckComment(check.id))" kind=figure_count spec_hash=\(specHash) — edit the check, not this file.
        source("test_runtime.R")

        minimum <- \(minFigures)

        # `plot.new` fires once per high-level plot (hist, plot, barplot) and
        # never for a low-level addition (lines, points, abline), so this counts
        # charts rather than drawing operations.  `grid.newpage` is the same
        # signal for grid-based graphics, so lattice and a printed ggplot object
        # count too where a course has installed them.  Both must be armed
        # before the submission runs.
        #
        # A ggplot object only draws when it is printed — assigning it to a
        # variable and never printing it produces no figure, in a notebook or
        # here.  Base graphics draw as a side effect and always count.
        .ck_figures <- 0L
        setHook("plot.new",     function(...) .ck_figures <<- .ck_figures + 1L)
        setHook("grid.newpage", function(...) .ck_figures <<- .ck_figures + 1L)

        student <- chickadee_load_student()

        figure_count <- .ck_figures
        if (figure_count < minimum) {
            failed(paste0(
                "Your notebook produced too few figures.\\n",
                "\(GeneratedMessage.expectedAtLeast)", minimum, "\\n",
                "\(GeneratedMessage.gotAtLeast)", figure_count))
        }

        passed(paste0("Your notebook produced ", figure_count, " figure(s) (minimum ", minimum, ")"))
        """
}

// MARK: - .cellContains

func renderRCellContains(_ check: NotebookCheck, specHash: String) -> String {
    let needle = check.containsText ?? ""
    let asRegex = check.regex ?? false
    let label = check.name ?? notebookCheckKindHandler(for: check.kind).defaultLabel(check)

    // PCRE (`perl = TRUE`) is the closest R gets to Python's `re`, so a pattern
    // authored against the Python renderer usually transfers unchanged.
    let matchExpr =
        asRegex
        ? "grepl(needle, cells, perl = TRUE)"
        : "grepl(needle, cells, fixed = TRUE)"

    let mustDifferBlock: String
    if let mustDiffer = check.mustDifferFrom {
        mustDifferBlock = """
            must_differ_from <- \(JSONValue.string(mustDiffer).rLiteral)
            # Whitespace-normalize both sides, so trailing newlines or a
            # re-indent don't disguise a copy of the example.
            .ck_normalize <- function(s) paste(strsplit(trimws(s), "[[:space:]]+")[[1L]], collapse = " ")
            reference <- .ck_normalize(must_differ_from)
            if (all(vapply(matched, function(s) identical(.ck_normalize(s), reference), logical(1)))) {
                failed(paste0(
                    "The cell containing `", needle, "` is identical to the example.\\n",
                    "\(GeneratedMessage.expected)a cell that contains `", needle, "` AND differs from the example\\n",
                    "\(GeneratedMessage.hint)write your own version, not a copy of the prompt's example"))
            }
            """
    } else {
        mustDifferBlock = "# (no must-differ-from constraint)"
    }

    // Deliberately not built on `rCheckPreamble`: this check reads the
    // submission's *source*, so it must not evaluate it — a student whose code
    // errors at the top level should still be told whether they wrote the cell.
    return """
        # Test: \(rCheckComment(label))
        # Generated from notebook check "\(rCheckComment(check.id))" kind=cell_contains spec_hash=\(specHash) — edit the check, not this file.
        source("test_runtime.R")

        needle <- \(JSONValue.string(needle).rLiteral)

        cells <- chickadee_student_cells()
        matched <- cells[\(matchExpr)]

        if (length(matched) == 0L) {
            failed(paste0(
                "No code cell in your notebook matches `", needle, "`.\\n",
                "\(GeneratedMessage.expected)at least one cell containing the pattern\\n",
                "  searched: ", length(cells), " code cell(s)"))
        }

        \(mustDifferBlock)

        passed(paste0("Found ", length(matched), " cell(s) containing `", needle, "`"))
        """
}
