// APIServer/Utilities/NotebookCheckRendererR.swift
//
// The R half of the notebook-check renderer: the data-frame family
// (.dataFrameShape, .dataFrameColumns, .dataFrameEquality, .seriesEquality)
// rendered as `.R` test scripts.
//
// Same separation as the pattern-family renderers: Python's generated bytes
// feed `spec_hash` and `TestSetupCache` keys and must never move, so R is
// added alongside rather than as branches inside the Python renderers.
//
// Mapping decisions worth knowing:
//   * A pandas DataFrame maps to a base-R `data.frame`. Tibbles and
//     `data.table`s inherit from it, so `nrow` / `ncol` / `names` work for a
//     course that later adds dplyr — no package is required at grading time.
//   * R has no Series. `.seriesEquality` therefore checks "a vector, or a
//     one-column data.frame" against the single-column expected CSV. That is
//     the honest analogue; pretending a Series type exists would not be.
//   * Expected data arrives in the same `_expected_<id>.csv` sidecar the
//     Python path uses, read with base `read.csv` (no dependency).
//
// The remaining six kinds are Python-only and rejected for R assignments at
// save time by `NotebookCheckValidator` — see `notebookCheckKindSupportsR`.

import Core
import Foundation

/// The notebook-check kinds that render in R today. Everything else is
/// rejected with a clear message rather than silently emitting Python for an
/// R assignment (which would produce a `.py` script the R suite can't run).
func notebookCheckKindSupportsR(_ kind: NotebookCheckKind) -> Bool {
    switch kind {
    case .dataFrameShape, .dataFrameColumns, .dataFrameEquality, .seriesEquality:
        return true
    case .numericArrayClose, .figureCount, .cellContains, .functionExists,
        .variableExists, .astStructure:
        return false
    }
}

/// Renders one notebook check as an R test script. Callers must have already
/// gated on `notebookCheckKindSupportsR`; an unsupported kind renders a script
/// that fails with an explicit message rather than trapping, so a spec that
/// slips past validation still produces a readable result.
func renderRNotebookCheck(_ check: NotebookCheck, specHash: String) -> String {
    switch check.kind {
    case .dataFrameShape: return renderRDataFrameShape(check, specHash: specHash)
    case .dataFrameColumns: return renderRDataFrameColumns(check, specHash: specHash)
    case .dataFrameEquality: return renderRDataFrameEquality(check, specHash: specHash)
    case .seriesEquality: return renderRSeriesEquality(check, specHash: specHash)
    case .numericArrayClose, .figureCount, .cellContains, .functionExists,
        .variableExists, .astStructure:
        return rUnsupportedCheck(check, specHash: specHash)
    }
}

// MARK: - Shared preamble

/// Header + runtime `source()` + the student environment. Every R check starts
/// here: `chickadee_load_student()` evaluates the submission expression by
/// expression, so a variable built by top-level calls is simply present (the
/// Python side needs `student_main_state()` to get the same effect).
private func rCheckPreamble(_ check: NotebookCheck, specHash: String, kindName: String) -> String {
    let label = check.name ?? notebookCheckKindHandler(for: check.kind).defaultLabel(check)
    return """
        # Test: \(rCheckComment(label))
        # Generated from notebook check "\(rCheckComment(check.id))" kind=\(kindName) spec_hash=\(specHash) — edit the check, not this file.
        source("test_runtime.R")

        student <- chickadee_load_student()
        """
}

/// Binds `actual` from the student environment, failing with a clear message
/// when the name was never defined. `expectation` completes the sentence
/// "expected: ...".
private func rFetchVariable(_ variable: String, expectation: String) -> String {
    """
    variable_name <- \(JSONValue.string(variable).rLiteral)

    .ck_missing <- structure(list(), class = "ck_missing")
    actual <- tryCatch(get(variable_name, envir = student, inherits = FALSE),
                       error = function(e) .ck_missing)
    if (inherits(actual, "ck_missing")) {
        failed(paste0(
            "Variable `", variable_name, "` is not defined in the student notebook.\\n",
            "  expected: \(expectation)"))
    }
    """
}

/// `data.frame` guard shared by the frame kinds. Tibbles / data.tables inherit
/// from `data.frame`, so `is.data.frame` accepts them too.
private func rRequireDataFrame(_ expectation: String) -> String {
    """
    if (!is.data.frame(actual)) {
        failed(paste0(
            "Variable `", variable_name, "` is not a data frame.\\n",
            "  expected: \(expectation)\\n",
            "  got:      ", class(actual)[[1L]]))
    }
    """
}

// MARK: - .dataFrameShape

func renderRDataFrameShape(_ check: NotebookCheck, specHash: String) -> String {
    let variable = check.variable ?? "df"
    let rows = check.expectedRows ?? 0
    let cols = check.expectedCols ?? 0
    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "data_frame_shape"))

        \(rFetchVariable(variable, expectation: "a data frame with \(rows) rows and \(cols) columns"))
        expected_rows <- \(rows)
        expected_cols <- \(cols)

        \(rRequireDataFrame("a data frame with \(rows) rows and \(cols) columns"))

        actual_rows <- nrow(actual)
        actual_cols <- ncol(actual)
        if (actual_rows != expected_rows || actual_cols != expected_cols) {
            failed(paste0(
                "Variable `", variable_name, "` has the wrong shape.\\n",
                "  expected: ", expected_rows, " rows x ", expected_cols, " columns\\n",
                "  got:      ", actual_rows, " rows x ", actual_cols, " columns"))
        }

        passed(paste0("`", variable_name, "` has ", actual_rows, " rows and ", actual_cols, " columns"))
        """
}

// MARK: - .dataFrameColumns

func renderRDataFrameColumns(_ check: NotebookCheck, specHash: String) -> String {
    let variable = check.variable ?? "df"
    let columns = check.expectedColumns ?? []
    let mode = check.columnMatch ?? .exact
    let expectedLiteral = JSONValue.array(columns.map(JSONValue.string)).rLiteral
    let expectation =
        mode == .exact
        ? "exactly these columns, in order" : "at least these columns"

    let comparison: String
    switch mode {
    case .exact:
        comparison = """
            if (length(actual_cols) != length(expected_cols) || !all(actual_cols == expected_cols)) {
                failed(paste0(
                    "Variable `", variable_name, "` has the wrong columns.\\n",
                    "  expected: ", chickadee_format(expected_cols), " (exact, in order)\\n",
                    "  got:      ", chickadee_format(actual_cols)))
            }
            """
    case .superset:
        comparison = """
            missing_cols <- expected_cols[!(expected_cols %in% actual_cols)]
            if (length(missing_cols) > 0L) {
                failed(paste0(
                    "Variable `", variable_name, "` is missing expected column(s).\\n",
                    "  missing:  ", chickadee_format(missing_cols), "\\n",
                    "  got:      ", chickadee_format(actual_cols)))
            }
            """
    }

    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "data_frame_columns"))

        \(rFetchVariable(variable, expectation: expectation))
        expected_cols <- \(expectedLiteral)

        \(rRequireDataFrame(expectation))

        actual_cols <- names(actual)
        if (is.null(actual_cols)) actual_cols <- character(0)

        \(comparison)

        passed(paste0("`", variable_name, "` has the expected columns"))
        """
}

// MARK: - .dataFrameEquality

func renderRDataFrameEquality(_ check: NotebookCheck, specHash: String) -> String {
    let variable = check.variable ?? "df"
    let sidecar = expectedCSVSidecarFilename(checkID: check.id)
    let rtol = JSONValue.double(check.rtol ?? 1e-5).rLiteral
    let atol = JSONValue.double(check.atol ?? 1e-8).rLiteral
    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "data_frame_equality"))

        \(rFetchVariable(variable, expectation: "a data frame equal to the expected data"))
        \(rRequireDataFrame("a data frame equal to the expected data"))

        expected <- read.csv(\(JSONValue.string(sidecar).rLiteral),
                             stringsAsFactors = FALSE, check.names = FALSE)
        rtol <- \(rtol)
        atol <- \(atol)

        if (nrow(actual) != nrow(expected) || ncol(actual) != ncol(expected)) {
            failed(paste0(
                "Variable `", variable_name, "` has the wrong shape.\\n",
                "  expected: ", nrow(expected), " rows x ", ncol(expected), " columns\\n",
                "  got:      ", nrow(actual), " rows x ", ncol(actual), " columns"))
        }

        if (!all(names(actual) == names(expected))) {
            failed(paste0(
                "Variable `", variable_name, "` has the wrong columns.\\n",
                "  expected: ", chickadee_format(names(expected)), "\\n",
                "  got:      ", chickadee_format(names(actual))))
        }

        # Numeric columns compare within tolerance; everything else compares as
        # text, so a factor and a character column holding the same labels agree.
        for (col in names(expected)) {
            exp_col <- expected[[col]]
            got_col <- actual[[col]]
            if (is.numeric(exp_col) && is.numeric(got_col)) {
                delta <- abs(as.numeric(got_col) - as.numeric(exp_col))
                allowed <- atol + rtol * abs(as.numeric(exp_col))
                bad <- which(!is.na(delta) & delta > allowed)
                na_mismatch <- which(is.na(got_col) != is.na(exp_col))
                bad <- sort(unique(c(bad, na_mismatch)))
                if (length(bad) > 0L) {
                    i <- bad[[1L]]
                    failed(paste0(
                        "Column `", col, "` differs from the expected data.\\n",
                        "  row:      ", i, "\\n",
                        "  expected: ", chickadee_format(exp_col[[i]]), "\\n",
                        "  got:      ", chickadee_format(got_col[[i]])))
                }
            } else {
                exp_chr <- as.character(exp_col)
                got_chr <- as.character(got_col)
                bad <- which(!(exp_chr == got_chr) | (is.na(exp_chr) != is.na(got_chr)))
                if (length(bad) > 0L) {
                    i <- bad[[1L]]
                    failed(paste0(
                        "Column `", col, "` differs from the expected data.\\n",
                        "  row:      ", i, "\\n",
                        "  expected: ", chickadee_format(exp_chr[[i]]), "\\n",
                        "  got:      ", chickadee_format(got_chr[[i]])))
                }
            }
        }

        passed(paste0("`", variable_name, "` matches the expected data (",
                      nrow(expected), " rows x ", ncol(expected), " columns)"))
        """
}

// MARK: - .seriesEquality

func renderRSeriesEquality(_ check: NotebookCheck, specHash: String) -> String {
    let variable = check.variable ?? "s"
    let sidecar = expectedCSVSidecarFilename(checkID: check.id)
    let rtol = JSONValue.double(check.rtol ?? 1e-5).rLiteral
    let atol = JSONValue.double(check.atol ?? 1e-8).rLiteral
    return """
        \(rCheckPreamble(check, specHash: specHash, kindName: "series_equality"))

        \(rFetchVariable(variable, expectation: "a vector matching the expected values"))
        # R has no Series: the analogue is a plain vector, and a one-column data
        # frame is accepted too so a student who kept the column wrapped still
        # passes.
        if (is.data.frame(actual)) {
            if (ncol(actual) != 1L) {
                failed(paste0(
                    "Variable `", variable_name, "` should be a single vector (or a one-column frame).\\n",
                    "  got:      a data frame with ", ncol(actual), " columns"))
            }
            actual <- actual[[1L]]
        }
        if (!is.atomic(actual)) {
            failed(paste0(
                "Variable `", variable_name, "` should be a vector.\\n",
                "  got:      ", class(actual)[[1L]]))
        }

        expected_frame <- read.csv(\(JSONValue.string(sidecar).rLiteral),
                                   stringsAsFactors = FALSE, check.names = FALSE)
        expected <- expected_frame[[1L]]
        rtol <- \(rtol)
        atol <- \(atol)

        if (length(actual) != length(expected)) {
            failed(paste0(
                "Variable `", variable_name, "` has the wrong length.\\n",
                "  expected: ", length(expected), " values\\n",
                "  got:      ", length(actual), " values"))
        }

        if (is.numeric(expected) && is.numeric(actual)) {
            delta <- abs(as.numeric(actual) - as.numeric(expected))
            allowed <- atol + rtol * abs(as.numeric(expected))
            bad <- which(!is.na(delta) & delta > allowed)
            bad <- sort(unique(c(bad, which(is.na(actual) != is.na(expected)))))
        } else {
            exp_chr <- as.character(expected)
            got_chr <- as.character(actual)
            bad <- which(!(exp_chr == got_chr) | (is.na(exp_chr) != is.na(got_chr)))
        }

        if (length(bad) > 0L) {
            i <- bad[[1L]]
            failed(paste0(
                "Variable `", variable_name, "` differs from the expected values.\\n",
                "  position: ", i, "\\n",
                "  expected: ", chickadee_format(expected[[i]]), "\\n",
                "  got:      ", chickadee_format(actual[[i]])))
        }

        passed(paste0("`", variable_name, "` matches the expected ", length(expected), " values"))
        """
}

// MARK: - Unsupported kinds

/// Fail-closed script for a kind that has no R renderer yet. Validation rejects
/// these at save time, so this only runs if a spec reached grading some other
/// way — better a clear message than a silently-passing test.
private func rUnsupportedCheck(_ check: NotebookCheck, specHash: String) -> String {
    """
    # Test: unsupported notebook check
    # Generated from notebook check "\(rCheckComment(check.id))" kind=\(check.kind.rawValue) spec_hash=\(specHash)
    source("test_runtime.R")

    errored(paste0("Notebook check kind '\(check.kind.rawValue)' is not supported for R ",
                   "assignments yet. Remove the check, or express it as a hand-written .R test."))
    """
}

/// Flattens a string for safe use inside a one-line `#` comment.
private func rCheckComment(_ text: String) -> String {
    text.replacingOccurrences(of: "\n", with: " ")
        .replacingOccurrences(of: "\r", with: " ")
}
