// APIServer/Utilities/PatternFamilyRendererCpp.swift
//
// The C++ half of the pattern-family renderer. Structured like the R / Lua /
// Octave renderers — one switch, one small body per kind — but what it emits
// is different in kind: a generated C++ case is a POSIX SHELL SCRIPT that
// carries its C++ source in a quoted heredoc, compiles it with g++, and
// exec's the binary. The wrapper rides the original shell-script contract
// (exit 0/1/2, last stdout line as shortResult), so the runner needs no C++
// dispatch and "no per-language build strategies in Swift" stays true — the
// build step lives in the generated script, beside the code it builds.
//
// The generated translation unit is: test_runtime.hpp (injected by the
// worker), optionally _ck_inputs.hpp (per-student values), then the
// student's file — copied by the wrapper to .ck_solution.cpp with `main`
// renamed, so a main-bearing submission still exposes its functions — then
// the test's own main(). Single-TU inclusion is what removes the
// declared-type problem the original C++ memo priced: the student's real
// definitions are in scope, so no prototype is ever declared and overload
// resolution runs against what they actually wrote.
//
// Decisions that came from measurement (docs/cpp-support.md):
//   * compile ~0.65s per test at -O0 — inside the default 10s per-test limit;
//   * performanceThreshold compiles -O2 (the one kind where optimization is
//     the point), and is supportable at all because C++ is native-only —
//     the two-substrate timing divergence that forces refusals elsewhere
//     cannot arise;
//   * a missing function is a compile error, so the existence guard treats
//     compile failure as the test's own FAIL rather than an error.

// THE PER-KIND RENDERERS ARE NOT HERE. Each one moved to
// `PatternFamilyRenderer+<Kind>.swift`, beside the other five languages'
// rendering of the same kind, so a kind can be reviewed across languages in one
// file. What remains is what is genuinely per-language: the kind dispatcher
// below, the call-context builder, the case header, the personalization
// preamble and the identifier/comment helpers.

import Core
import Foundation

// MARK: - Per-case C++ rendering

/// Renders one enabled case of `family` as a shell wrapper + embedded C++.
func renderCppPatternCase(
    family: PatternFamily,
    case c: PatternCase,
    sectionVariables: [FamilyVariable],
    specHash: String,
    perStudentNames: Set<String> = []
) -> String {
    let context = cppCallContext(
        for: family, case: c, perStudentNames: perStudentNames)
    let target = family.functionName

    let body: String
    switch family.kind {
    case .boundaryEquality:
        body = cppEqualityBody(target: target, context: context, c: c, unordered: false)
    case .unorderedEquality:
        body = cppEqualityBody(target: target, context: context, c: c, unordered: true)
    case .approximateEquality:
        body = cppApproximateBody(target: target, context: context, c: c, family: family)
    case .variableEquality:
        body = cppVariableEqualityBody(family: family, context: context, c: c)
    case .returnTypeCheck:
        body = cppReturnTypeBody(target: target, context: context, c: c)
    case .exceptionExpected:
        body = cppExceptionBody(target: target, context: context, c: c)
    case .performanceThreshold:
        body = cppPerformanceBody(target: target, context: context, c: c)
    case .stdoutEquality:
        body = cppStdoutBody(target: target, context: context, c: c)
    case .differential:
        body = cppDifferentialBody(family: family, context: context, c: c)
    }

    let source = [
        cppGeneratedCaseHeader(family: family, case: c, specHash: specHash),
        "#include \"test_runtime.hpp\"",
        context.usesInputs ? cppInputsInclude : "",
        cppStudentInclude,
        cppVariableDecls(sectionVariables: sectionVariables, family: family),
        // The reference is a file-scope definition, so it goes beside the
        // student's translation unit rather than inside main().
        family.kind == .differential ? cppReferenceBlock(family) : "",
        "int main() {",
        cppIndent(context.declBlock + body),
        "}",
    ]
    .filter { !$0.isEmpty }
    .joined(separator: "\n")

    return cppShellWrapper(
        embeddedSource: source,
        stem: "\(family.id)_\(c.key)",
        optimization: family.kind == .performanceThreshold ? "-O2" : "-O0")
}

/// The 0-point existence guard other kinds depend on. Referencing the
/// function's address fails to compile when the name is absent — reported as
/// a FAILURE (exit 1), not an error: a missing function is the student's to
/// fix, exactly like the other languages' guards.
func renderCppExistenceGuard(family: PatternFamily, specHash: String) -> String {
    let target = family.functionName
    let source = """
        \(cppComment("Generated by Chickadee — existence guard for family '\(family.id)'."))
        \(cppComment("spec_hash: \(specHash)"))
        #include "test_runtime.hpp"
        \(cppStudentInclude)
        int main() {
            (void)sizeof(&\(target));
            ck::passed("\(target) is defined");
        }
        """
    return cppShellWrapper(
        embeddedSource: source,
        stem: "\(family.id)_\(patternExistenceGuardCaseKey)",
        optimization: "-O0",
        compileFailureIsTestFailure: true,
        compileFailureMessage:
            "`\(target)` is not defined (or the submission does not compile)")
}

// MARK: - The shell wrapper

private func cppShellWrapper(
    embeddedSource: String,
    stem: String,
    optimization: String,
    compileFailureIsTestFailure: Bool = false,
    compileFailureMessage: String = ""
) -> String {
    let sourceFile = ".ck_src_\(stem).cpp"
    let binaryFile = ".ck_bin_\(stem)"
    let failureFooter = shellSingleQuoted("{\"shortResult\": \"\(compileFailureMessage)\"}")
    // The build log goes to a file and is emitted only when the compile FAILS.
    // Sent straight to stderr it also rode a SUCCESSFUL compile into the
    // student's `longResult`, so a passing test displayed g++'s warnings as
    // though they were output worth reading (#1349).
    let compileCommand =
        "g++ -std=c++20 \(optimization) \(sourceFile) -o \(binaryFile) >.ck_build_log 2>&1"
    let compileStep: String
    if compileFailureIsTestFailure {
        compileStep = """
            if ! \(compileCommand); then
                cat .ck_build_log 1>&2
                printf '%s\\n' \(failureFooter)
                exit 1
            fi
            """
    } else {
        compileStep = """
            if ! \(compileCommand); then
                cat .ck_build_log 1>&2
                exit 2
            fi
            """
    }
    // A missing submission is the STUDENT's to fix, so on the existence guard
    // it is a graded fail with a readable message — the same answer Java has
    // always given, where javac's failure ran through the guard's
    // compile-failure branch. C++ reported `error` here for the same student
    // state, because this check runs before the compile step (#1349).
    let missingSubmissionStep =
        compileFailureIsTestFailure
        ? """
        if [ ! -f "$student_file" ]; then
            printf '%s\\n' \(failureFooter)
            exit 1
        fi
        """
        : """
        if [ ! -f "$student_file" ]; then
            echo "No C++ submission file was found to grade." 1>&2
            exit 2
        fi
        """
    return """
        #!/bin/sh
        # Generated by Chickadee — do not edit. The C++ source below is the
        # test; this wrapper locates the submission, compiles one translation
        # unit with the injected runtime, and runs it under the ordinary
        # shell-script contract.
        student_file=""
        if [ -f .chickadee_student_module ]; then
            student_file=$(cat .chickadee_student_module)
        fi
        if [ ! -f "$student_file" ]; then
            for candidate in *.cpp; do
                case "$candidate" in
                    .ck_*|*test_*) ;;
                    *) student_file="$candidate"; break ;;
                esac
            done
        fi
        \(missingSubmissionStep)
        cp "$student_file" .ck_solution.cpp
        cat > \(sourceFile) <<'CHICKADEE_GENERATED_SOURCE'
        \(embeddedSource)
        CHICKADEE_GENERATED_SOURCE
        \(compileStep)
        exec ./\(binaryFile)
        """ + "\n"
}

/// The student include, with `main` renamed so a main-bearing submission (an
/// intro "write a program" file) still exposes its functions to the test.
/// The macro renames the token only — string literals and comments are
/// untouched by the preprocessor.
private let cppStudentInclude = """
    #define main ck_student_main
    #include ".ck_solution.cpp"
    #undef main
    """

/// Emitted only when the case references a per-student input.
/// `__has_include` keeps a stale generated test harmless when the inputs
/// file is absent: the reference then fails to compile loudly rather than
/// grading against a missing value.
private let cppInputsInclude = """
    #if __has_include("_ck_inputs.hpp")
    #include "_ck_inputs.hpp"
    #endif
    """

private func cppGeneratedCaseHeader(
    family: PatternFamily, case c: PatternCase, specHash: String
) -> String {
    let label = c.label.isEmpty ? "" : " (\(c.label))"
    return """
        \(cppComment("Generated by Chickadee — pattern family '\(family.id)', case '\(c.key)'\(label)."))
        \(cppComment("Edit the family, not this file. spec_hash: \(specHash)"))
        """
}

/// Section + family variables as file-scope consts. C++ forbids redefining a
/// name in one scope, so the `family > section` shadowing the other languages
/// get from later-assignment-wins is spelled here by emitting the family's
/// value and FILTERING the section duplicate out.
private func cppVariableDecls(
    sectionVariables: [FamilyVariable], family: PatternFamily
) -> String {
    var seen = Set<String>()
    var declarations: [String] = []
    for variable in family.variables + sectionVariables
    where seen.insert(variable.name).inserted {
        declarations.append(
            "inline const auto \(variable.name) = \(variable.value.cppLiteral);")
    }
    return declarations.joined(separator: "\n")
}

// MARK: - Call context

/// The rendered pieces a kind body composes: argument bindings, the call's
/// argument list, and the C++ expression fragment that previews the inputs in
/// a failure message.
struct CppCallContext {
    let declBlock: String  // "auto x = ...;" lines opening main(), or ""
    let callArgs: String  // "x, y"
    let inputLine: String  // C++ expr: "input: x=..., y=...\n" (or no-input)
    let usesInputs: Bool  // any per-student reference → include _ck_inputs.hpp
    let expectedExpression: String  // per-student ref, variable ref, or literal
}

private func cppCallContext(
    for family: PatternFamily, case c: PatternCase, perStudentNames: Set<String>
) -> CppCallContext {
    let argNames: [String] = {
        if !family.paramNames.isEmpty { return family.paramNames }
        return c.args.indices.map { "arg_\($0 + 1)" }
    }()
    let provided: [Bool] = {
        guard !c.argsProvided.isEmpty else { return Array(repeating: true, count: argNames.count) }
        return (0..<argNames.count).map { i in i < c.argsProvided.count ? c.argsProvided[i] : true }
    }()
    let varRefs: [String?] = {
        guard !c.argVarRefs.isEmpty else { return Array(repeating: nil, count: argNames.count) }
        return (0..<argNames.count).map { i in i < c.argVarRefs.count ? c.argVarRefs[i] : nil }
    }()

    var usesInputs = false
    func reference(_ name: String) -> String {
        if perStudentNames.contains(name) {
            usesInputs = true
            return "ck_inputs::\(name)"
        }
        return name
    }

    var declLines: [String] = []
    var callParts: [String] = []
    var previewParts: [String] = []
    for (idx, name) in argNames.enumerated() {
        guard idx < provided.count ? provided[idx] : true else {
            // C++ has no keyword arguments either: an omission ends the list,
            // and the callee's defaulted parameters take over — the same
            // partial call a student could write themselves.
            break
        }
        if let refName = idx < varRefs.count ? varRefs[idx] : nil {
            declLines.append("auto \(name) = \(reference(refName));")
        } else if idx < c.args.count {
            declLines.append("auto \(name) = \(c.args[idx].cppLiteral);")
        }
        callParts.append(name)
        previewParts.append("\"\(name)=\" + ck::format(\(name))")
    }

    let inputLine: String
    if previewParts.isEmpty {
        inputLine = "\"\(GeneratedMessage.input)(no input)\\n\""
    } else {
        let joined = previewParts.joined(separator: " + \", \" + ")
        inputLine = "\"\(GeneratedMessage.input)\" + \(joined) + \"\\n\""
    }

    // The expected value resolves with the same reference rules as the
    // arguments: a per-student name → ck_inputs::, another name → the
    // file-scope variable, no reference → the rendered literal.
    let expectedExpression: String
    if let ref = c.expectedVarRef {
        expectedExpression = reference(ref)
    } else {
        expectedExpression = c.expected.cppLiteral
    }

    return CppCallContext(
        declBlock: declLines.isEmpty ? "" : declLines.joined(separator: "\n") + "\n",
        callArgs: callParts.joined(separator: ", "),
        inputLine: inputLine,
        usesInputs: usesInputs,
        expectedExpression: expectedExpression
    )
}

// MARK: - Kind bodies

/// The reference call, in its own try/catch so a throwing reference is reported
/// as a broken TEST rather than a broken submission. `auto expected` is declared
/// outside the try (and default-initialised) so the comparison below can see it;
/// `ck::errored` is `[[noreturn]]`, so the uninitialised path is unreachable.
func cppDifferentialExpected(family: PatternFamily, context: CppCallContext) -> String {
    """
    decltype(\(family.differentialReferenceName)(\(context.callArgs))) expected{};
    try {
        expected = \(family.differentialReferenceName)(\(context.callArgs));
    } catch (const std::exception& ck_ref_e) {
        ck::errored(std::string("\(GeneratedMessage.referenceFailed)\\n")
            + \(context.inputLine)
            + "\(GeneratedMessage.error)" + ck_ref_e.what());
    }
    """
}

/// The instructor's reference implementation at file scope, above `main()`.
private func cppReferenceBlock(_ family: PatternFamily) -> String {
    [
        cppComment("Instructor's reference implementation, rendered verbatim."),
        family.referenceImplementation ?? "",
    ].joined(separator: "\n")
}

/// Wraps a body in the shared unexpected-exception handler: a throw from
/// the student's code is a graded FAIL with the same first line every other
/// language uses, never a std::terminate.
///
/// BOTH arms are required. `catch (const std::exception&)` alone left
/// `throw "negative input";` and `throw -1;` — the shapes an intro course
/// teaches before `<stdexcept>` — to escape `main`, where `std::terminate`
/// aborts the process (measured: SIGABRT, exit 134, which the worker maps to
/// status `error` with a raw "terminate called after throwing" on stderr).
/// The equivalent Java submission has always been a clean `fail`, because
/// `javaGuarded` catches `Throwable`. `expect_throw` already had the
/// `catch (...)` arm, so the omission was inconsistent inside one feature.
func cppGuarded(_ inner: String, inputLine: String) -> String {
    """
    try {
    \(cppIndent(inner))
    } catch (const std::exception& ck_e) {
        ck::failed(std::string("\(GeneratedMessage.unexpectedException)\\n")
            + \(inputLine)
            + "\(GeneratedMessage.error)" + ck_e.what());
    } catch (...) {
        ck::failed(std::string("\(GeneratedMessage.unexpectedException)\\n")
            + \(inputLine)
            + "\(GeneratedMessage.error)(a non-std exception)");
    }
    """
}

// MARK: - Small utilities

private func cppIndent(_ block: String) -> String {
    block.split(separator: "\n", omittingEmptySubsequences: false)
        .map { $0.isEmpty ? "" : "    \($0)" }
        .joined(separator: "\n")
}
