// APIServer/Utilities/PatternFamilyRenderer.swift
//
// Expands a PatternFamily into a deterministic set of Python test scripts
// plus matching TestSuiteEntry metadata.  Rendering is pure: identical input
// produces byte-identical output so the same spec across regenerations
// yields stable diffs.
//
// The generated source uses the same test_runtime helpers and rich-feedback
// format as the hand-authored templates, so the runner cannot distinguish a
// generated script from one an instructor wrote by hand.
//
// This file owns the family-level entry points (case expansion, existence
// guard, filenames, spec hash) and the per-kind dispatch.  The per-kind
// `render*` bodies live in PatternFamilyRenderer+<Kind>.swift, sharing the
// template helpers in PatternFamilyRenderer+Shared.swift (June 2026 audit
// split).  Generated bytes feed `spec_hash` and `TestSetupCache` keys, so
// the split is Swift-side organization only — output is byte-identical.

import Core
import Foundation

/// One rendered case: a filename, the Python source to write to the zip, and
/// enough metadata to construct a TestSuiteEntry that points back at the
/// family via `generatedBy`.
struct GeneratedScript: Equatable {
    let filename: String
    let source: String
    let tier: TestTier
    let points: Int
    let displayName: String
    let caseKey: String
    let familyID: String
    /// The resolved per-test execution time limit (seconds) for this generated
    /// entry, or nil to inherit the assignment-wide default. For a case it is
    /// `case.resolvedTimeLimit(defaults:)`; for the existence guard it is the
    /// family default. A non-positive resolved value is normalised to nil.
    let timeLimitSeconds: Int?
}

/// Top-level entry point.  Returns one `GeneratedScript` per **enabled** case
/// in the family; disabled cases are skipped.  Ordering follows `family.cases`.
///
/// `sectionVariables` (v0.4.100+) are prepended to every generated test
/// before the family's own variables.  `globalVariables` (Slice 1) are
/// prepended before section variables.  Effective precedence in the
/// generated Python is `family > section > global` (Python's
/// last-assignment-wins on identical names); the spec_hash reflects all
/// three lists.
func renderPatternFamily(
    _ family: PatternFamily,
    sectionVariables: [FamilyVariable] = [],
    globalVariables: [FamilyVariable] = [],
    perStudentNames: Set<String> = []
) -> [GeneratedScript] {
    // Pre-combine globals and section vars into a single "scope" list so the
    // existing render-* helpers stay parameterised on a single prepend list.
    let scopeVariables = globalVariables + sectionVariables
    let hash = patternFamilySpecHash(
        family,
        sectionVariables: sectionVariables,
        globalVariables: globalVariables)
    return family.cases.compactMap { c in
        guard c.enabled else { return nil }
        return renderCase(
            family: family, case: c,
            sectionVariables: scopeVariables, specHash: hash,
            perStudentNames: perStudentNames)
    }
}

/// All filenames this family **would** produce if every case were enabled.
/// Used when diffing old/new specs so we can detect stale files that need
/// deleting, even for cases that were previously disabled.
func patternFamilyAllGeneratedFilenames(_ family: PatternFamily) -> [String] {
    var names = family.cases.map { c in
        generatedScriptFilename(
            familyID: family.id,
            caseKey: c.key,
            tier: c.resolvedTier(defaults: family.defaults)
        )
    }
    // The auto-existence guard isn't a `case`, but its file is generated for
    // function-calling kinds — list it here so the diff in
    // `applyPatternFamilies` deletes a stale guard when the family's default
    // tier changes, the kind switches to one that doesn't call a function, or
    // the family is removed, and so the filename-collision checks see it.
    if patternKindHandler(for: family.kind).requiresFunctionName {
        names.append(
            generatedScriptFilename(
                familyID: family.id,
                caseKey: patternExistenceGuardCaseKey,
                tier: family.defaults.tier
            ))
    }
    return names
}

// MARK: - Existence guard

/// Reserved case key for a family's auto-generated existence guard.  A real
/// case may not use this key for a function-calling kind (the validator
/// rejects it), so the guard's deterministic filename
/// (`{tier}test_{familyID}_exists.py`) can never collide with a case file.
let patternExistenceGuardCaseKey = "exists"

/// The existence-guard script for `family`, or nil when the family doesn't
/// call a function (`.variableEquality` already self-guards each case's
/// variable) or has no enabled cases (nothing to gate).
///
/// The guard is a 0-point test that checks the target function is defined and
/// callable.  Every generated case `dependsOn` it (wired in
/// `applyPatternFamilies`), so a missing/!callable function produces one clear
/// "`fn` is not defined" failure and the cases auto-skip through the runner's
/// dependency gate — instead of N opaque AttributeError tracebacks.  Its tier
/// follows the family default so the failure is visible at the same level as
/// the cases it protects.
func existenceGuard(
    for family: PatternFamily,
    sectionVariables: [FamilyVariable] = [],
    globalVariables: [FamilyVariable] = []
) -> GeneratedScript? {
    guard patternKindHandler(for: family.kind).requiresFunctionName,
        family.cases.contains(where: \.enabled)
    else { return nil }
    let hash = patternFamilySpecHash(
        family, sectionVariables: sectionVariables, globalVariables: globalVariables)
    let tier = family.defaults.tier
    let label = "\(family.functionName) is defined"
    let nameLiteral = "\"" + escapeForPythonStringLiteral(family.functionName) + "\""
    // Mirrors the `getattr(..., _MISSING)` sentinel that `variableEquality`
    // (and the function_exists notebook check) already use — `_MISSING`
    // distinguishes "not defined" from "defined as None"; `callable` catches a
    // student who shadowed the name with a non-function value.
    let source = """
        # Test: \(label)
        # Generated from pattern family \"\(escapeForPythonStringLiteral(family.name))\" [\(family.id)] spec_hash=\(hash) — edit the family, not this file.
        # Existence guard: the family's cases depend on this test, so a missing
        # or non-callable target fails once here and the cases skip instead of
        # raising N AttributeErrors.

        function_name = \(nameLiteral)

        _MISSING = object()
        target = getattr(student_module, function_name, _MISSING)
        if target is _MISSING:
            failed(f"`{function_name}` is not defined — define a function named `{function_name}` in your submission.")
        if not callable(target):
            failed(f"`{function_name}` is defined but is not a function (got {type(target).__name__}).")
        passed(f"`{function_name}` is defined")
        """
    return GeneratedScript(
        filename: generatedScriptFilename(
            familyID: family.id, caseKey: patternExistenceGuardCaseKey, tier: tier),
        source: source,
        tier: tier,
        points: 0,
        displayName: label,
        caseKey: patternExistenceGuardCaseKey,
        familyID: family.id,
        // The guard applies to all the family's generated entries, so it
        // inherits the family-level limit (the cases inherit it too unless
        // they set their own).
        timeLimitSeconds: normalizedGeneratedTimeLimit(family.defaults.timeLimitSeconds)
    )
}

/// Stable filename for one case.  Format: `{tier}test_{familyID}_{caseKey}.py`.
/// The tier prefix mirrors the convention used elsewhere in the codebase so
/// the runner's student-module loader correctly excludes generated test files.
func generatedScriptFilename(familyID: String, caseKey: String, tier: TestTier) -> String {
    "\(tierFilenamePrefix(tier))test_\(familyID)_\(caseKey).py"
}

/// 16-character hex prefix of a SHA-256 over the canonical JSON encoding of
/// the family (sorted keys).  Stable for a given spec; changes when anything
/// about the family changes.
func patternFamilySpecHash(
    _ family: PatternFamily,
    sectionVariables: [FamilyVariable] = [],
    globalVariables: [FamilyVariable] = []
) -> String {
    let encoder = JSONEncoder()
    encoder.outputFormatting = [.sortedKeys]
    let familyData = (try? encoder.encode(family)) ?? Data()
    // Mix section + global variables into the hash so changing either busts
    // the manifest cache the same way changing the family itself does.
    let sectionVarsData = (try? encoder.encode(sectionVariables)) ?? Data()
    let globalVarsData = (try? encoder.encode(globalVariables)) ?? Data()
    var buf = Data()
    buf.append(familyData)
    buf.append(sectionVarsData)
    buf.append(globalVarsData)
    return String(sha256HexDigest(buf).prefix(16))
}

// MARK: - Per-kind dispatch

private func renderCase(
    family: PatternFamily,
    case c: PatternCase,
    sectionVariables: [FamilyVariable],
    specHash: String,
    perStudentNames: Set<String>
) -> GeneratedScript {
    let source = patternKindHandler(for: family.kind).render(
        family: family, case: c,
        sectionVariables: sectionVariables, specHash: specHash,
        perStudentNames: perStudentNames)

    let tier = c.resolvedTier(defaults: family.defaults)
    return GeneratedScript(
        filename: generatedScriptFilename(familyID: family.id, caseKey: c.key, tier: tier),
        source: source,
        tier: tier,
        points: c.resolvedPoints(defaults: family.defaults),
        displayName: c.label,
        caseKey: c.key,
        familyID: family.id,
        timeLimitSeconds: normalizedGeneratedTimeLimit(c.resolvedTimeLimit(defaults: family.defaults))
    )
}

/// Maps a resolved generated-entry time limit to the value persisted on the
/// manifest: a positive value passes through, while nil / 0 / negative collapse
/// to nil ("no override — inherit the assignment-wide default"). Used at every
/// generated `GeneratedScript` construction so a 0/negative never reaches the
/// manifest.
func normalizedGeneratedTimeLimit(_ value: Int?) -> Int? {
    (value ?? 0) > 0 ? value : nil
}
