// APIServer/Utilities/PatternFamilyRenderer+Shared.swift
//
// Template helpers shared by every per-kind render function (call context,
// variable declarations, the two-line generated-case header, and the
// per-student personalization preamble).  Split from
// PatternFamilyRenderer.swift (June 2026 audit).
//
// These declarations were `private` when all the render functions lived in
// one file; they are internal now so the PatternFamilyRenderer+<Kind>.swift
// files (same module) can keep calling them.  Generated bytes are unchanged.

import Core
import Foundation

/// Per-case call context: a bundle of the four Python fragments every kind
/// needs when rendering a function call with optional omitted parameters.
/// Empty cells on defaulted params are skipped in the declarations and
/// omitted from the call; the call switches from positional to keyword
/// form after the first gap so Python's argument-binding rules hold.
struct CallContext {
    /// One line per provided arg: `name = <pythonLiteral>`.  Omitted args
    /// get no declaration.
    let declLines: String
    /// The parenthesised arg list as it appears inside
    /// `student_module.func(<here>)`.  Leading contiguous provided args are
    /// positional; anything after a gap becomes a kwarg.  Empty when the
    /// instructor provided no args at all.
    let callArgs: String
    /// Python expression interpolated into the `input: …` f-string at the
    /// top of every failure message.  Only provided args appear.
    let inputLineLiteral: String
    /// Expression interpolated into the `passed(...)` / `... returned`
    /// success message to echo the arg values back to the student.
    let callReprExpr: String
}

func callContext(for family: PatternFamily, case c: PatternCase) -> CallContext {
    let argNames: [String] = {
        if !family.paramNames.isEmpty { return family.paramNames }
        return c.args.indices.map { "arg_\($0 + 1)" }
    }()

    // argsProvided == [] (empty) means pre-v0.4.94 behaviour: every arg
    // was provided.  Non-empty must match args.count (enforced by the
    // PatternCase initialiser).  Pad defensively to `argNames.count` in
    // case paramNames and args have drifted apart (validation would
    // normally catch that, but failing closed is cheaper than crashing).
    let provided: [Bool] = {
        guard !c.argsProvided.isEmpty else {
            return Array(repeating: true, count: argNames.count)
        }
        if c.argsProvided.count == argNames.count { return c.argsProvided }
        return (0..<argNames.count).map { i in
            i < c.argsProvided.count ? c.argsProvided[i] : true
        }
    }()

    // argVarRefs == [] (empty) means "no variable references" — the
    // pre-v0.4.94 shape where every arg is a literal.  A non-nil entry
    // at position `i` names a family variable to pass instead of the
    // literal.  Padded defensively for the same reason as `provided`.
    let varRefs: [String?] = {
        guard !c.argVarRefs.isEmpty else {
            return Array(repeating: nil, count: argNames.count)
        }
        if c.argVarRefs.count == argNames.count { return c.argVarRefs }
        return (0..<argNames.count).map { i in
            i < c.argVarRefs.count ? c.argVarRefs[i] : nil
        }
    }()

    var declLineList: [String] = []
    var callArgsParts: [String] = []
    var previewParts: [String] = []
    var reprParts: [String] = []
    var sawOmission = false
    for (idx, name) in argNames.enumerated() {
        let isProvided = idx < provided.count ? provided[idx] : true
        if !isProvided {
            sawOmission = true
            continue
        }
        // Variable reference: assign the param name directly from the
        // family variable (no local literal declaration needed — the
        // variable already lives at module scope, prepended by
        // `familyVariableDecls()`).
        let varRef = idx < varRefs.count ? varRefs[idx] : nil
        if let refName = varRef {
            declLineList.append("\(name) = \(refName)")
        } else if idx < c.args.count {
            declLineList.append("\(name) = \(c.args[idx].pythonLiteral)")
        }
        // Switch to kwargs the moment we pass any omitted arg — Python
        // forbids positional-after-keyword, and `fn(a, c=...)` is how we
        // tell Python "pass a positionally, skip b, fill c".
        callArgsParts.append(sawOmission ? "\(name)=\(name)" : name)
        previewParts.append("\(name)={\(name)!r}")
        reprParts.append("{\(name)!r}")
    }

    let inputLineLiteral: String
    if previewParts.isEmpty {
        inputLineLiteral = #""\#(GeneratedMessage.input)(no input)\n""#
    } else {
        inputLineLiteral = "f\"\(GeneratedMessage.input)\(previewParts.joined(separator: ", "))\\n\""
    }

    return CallContext(
        declLines: declLineList.joined(separator: "\n"),
        callArgs: callArgsParts.joined(separator: ", "),
        inputLineLiteral: inputLineLiteral,
        callReprExpr: reprParts.joined(separator: ", ")
    )
}

/// Renders the `name = <pythonLiteral>` preamble for every variable in
/// scope for this generated test: scope variables first (global + section,
/// pre-combined by the caller in `renderPatternFamily`), then family
/// variables.  Python's last-assignment-wins semantics means a family
/// variable with the same name shadows a section variable, which shadows
/// a global — that's the intended precedence ("family > section > global").
/// Empty string when no variables.
///
/// Takes the language explicitly. It used to inherit `emit`'s `.python`
/// default, which was true of every caller — the eight files below are the
/// Python arm of `renderCase` — but true by circumstance rather than by
/// statement, and there is nothing in the signature that would have stopped a
/// non-Python renderer from calling it and silently getting Python
/// declarations.
func combinedVariableDecls(
    sectionVariables: [FamilyVariable],
    family: PatternFamily,
    language: AssignmentLanguage
) -> String {
    TestScriptVariablePrepender.emit(sectionVariables + family.variables, language: language)
}

/// The two-line header every generated case starts with:
///
///     # Test: <case label>
///     # Generated from pattern family "<name>" [<id>] spec_hash=<hash> — edit the family, not this file.
///
/// The `# Test:` line MUST come first so `test_runtime._first_comment_label()`
/// picks up the case label.  Consolidated in v0.4.185 (Phase 5.A) — pre-fix
/// this header was open-coded in all 7 kind-specific render functions.
func generatedCaseHeader(family: PatternFamily, case c: PatternCase, specHash: String) -> String {
    """
    # Test: \(c.label)
    # Generated from pattern family \"\(escapeForPythonStringLiteral(family.name))\" [\(family.id)] spec_hash=\(specHash) — edit the family, not this file.
    """
}

// Hints are no longer baked into the generated Python (v0.4.229).  An
// instructor hint — per-case `resolvedHint(defaults:)` for families,
// `NotebookCheck.hint` for checks, `TestSuiteEntry.hint` for raw scripts —
// is surfaced uniformly as a "💡 Hint" callout on failing tests at
// results-display time (see the `hintByFilename` join in
// `WebRoutes+Submission.swift`), decoupled from the test script.

// MARK: - Personalization (per-student inputs)

/// The Python expression assigned to `expected` in a generated equality case:
/// a bare identifier when the case pins `expectedVarRef` (bound from a
/// per-student `_ck_inputs` value), otherwise the baked literal.
func expectedExpression(for c: PatternCase) -> String {
    if let ref = c.expectedVarRef, !ref.isEmpty { return ref }
    return c.expected.pythonLiteral
}

/// Names referenced by this case — arg `$name` refs plus the expected ref —
/// that name a per-student `=` expression (vs. a literal variable).  Sorted +
/// deduped so generated output is deterministic.
func perStudentRefsForCase(_ c: PatternCase, perStudentNames: Set<String>) -> [String] {
    guard !perStudentNames.isEmpty else { return [] }
    var names = Set<String>()
    for ref in c.argVarRefs.compactMap({ $0 }) where perStudentNames.contains(ref) {
        names.insert(ref)
    }
    if let ref = c.expectedVarRef, perStudentNames.contains(ref) { names.insert(ref) }
    return names.sorted()
}

/// The per-student input preamble for a generated case, or "" when the case
/// references no per-student expressions.  Loads `_ck_inputs.py` (written by
/// the runner from the job's resolved values) by path — so it works
/// regardless of sys.path — fails the test closed with a clear message when a
/// value is missing (e.g. no assignment seed), then binds each referenced name
/// as a module-level global the case body uses by bare identifier.
func personalizationPreambleForCase(
    _ c: PatternCase, perStudentNames: Set<String>
) -> String {
    let names = perStudentRefsForCase(c, perStudentNames: perStudentNames)
    guard !names.isEmpty else { return "" }
    let keyItems = names.map { "\"\(escapeForPythonStringLiteral($0))\"" }
    let keyTuple = names.count == 1 ? "(\(keyItems[0]),)" : "(\(keyItems.joined(separator: ", ")))"
    let bindings =
        names
        .map { "\($0) = _ck[\"\(escapeForPythonStringLiteral($0))\"]" }
        .joined(separator: "\n")
    return """
        # Per-student personalization inputs, resolved at grading time from the
        # assignment seed (see _ck_inputs.py, written by the runner).  Do not edit.
        import importlib.util as _ck_ilu, os as _ck_os
        _ck = {}
        if _ck_os.path.exists("_ck_inputs.py"):
            _ck_spec = _ck_ilu.spec_from_file_location("_ck_inputs", "_ck_inputs.py")
            _ck_mod = _ck_ilu.module_from_spec(_ck_spec)
            _ck_spec.loader.exec_module(_ck_mod)
            _ck = getattr(_ck_mod, "_ck", {})
        for _ck_k in \(keyTuple):
            if _ck_k not in _ck:
                failed(f"Personalization input '{_ck_k}' is unavailable — is the assignment seed set?")
        \(bindings)
        """
}

// MARK: - Helpers
//
// `tierFilenamePrefix(_:)` and `escapeForPythonStringLiteral(_:)` live in
// PythonScriptHelpers.swift — shared with NotebookCheckRenderer.
