// APIServer/Utilities/PatternFamilyRendererCpp.swift
//
// The C++ half of the pattern-family renderer. Structured like the R / Lua /
// Octave renderers — one switch, one small body per kind — but what it emits
// is different in kind: a generated C++ case is a POSIX SHELL SCRIPT that
// carries its C++ source in a quoted heredoc, compiles it with g++, and
// exec's the binary. The wrapper rides the original shell-script contract
// (exit 0/1/2, last stdout line as shortResult), so the runner needs no C++
// dispatch and "no per-language build strategies in Swift" stays true — the
// build step lives in the generated script, beside the code it builds.
//
// The generated translation unit is: test_runtime.hpp (injected by the
// worker), optionally _ck_inputs.hpp (per-student values), then the
// student's file — copied by the wrapper to .ck_solution.cpp with `main`
// renamed, so a main-bearing submission still exposes its functions — then
// the test's own main(). Single-TU inclusion is what removes the
// declared-type problem the original C++ memo priced: the student's real
// definitions are in scope, so no prototype is ever declared and overload
// resolution runs against what they actually wrote.
//
// Decisions that came from measurement (docs/cpp-support.md):
//   * compile ~0.65s per test at -O0 — inside the default 10s per-test limit;
//   * performanceThreshold compiles -O2 (the one kind where optimization is
//     the point), and is supportable at all because C++ is native-only —
//     the two-substrate timing divergence that forces refusals elsewhere
//     cannot arise;
//   * a missing function is a compile error, so the existence guard treats
//     compile failure as the test's own FAIL rather than an error.

import Core
import Foundation

// MARK: - Per-case C++ rendering

/// Renders one enabled case of `family` as a shell wrapper + embedded C++.
func renderCppPatternCase(
    family: PatternFamily,
    case c: PatternCase,
    sectionVariables: [FamilyVariable],
    specHash: String,
    perStudentNames: Set<String> = []
) -> String {
    let context = cppCallContext(
        for: family, case: c, perStudentNames: perStudentNames)
    let target = family.functionName

    let body: String
    switch family.kind {
    case .boundaryEquality:
        body = cppEqualityBody(target: target, context: context, c: c, unordered: false)
    case .unorderedEquality:
        body = cppEqualityBody(target: target, context: context, c: c, unordered: true)
    case .approximateEquality:
        body = cppApproximateBody(target: target, context: context, c: c, family: family)
    case .variableEquality:
        body = cppVariableEqualityBody(family: family, context: context, c: c)
    case .returnTypeCheck:
        body = cppReturnTypeBody(target: target, context: context, c: c)
    case .exceptionExpected:
        body = cppExceptionBody(target: target, context: context, c: c)
    case .performanceThreshold:
        body = cppPerformanceBody(target: target, context: context, c: c)
    case .stdoutEquality:
        body = cppStdoutBody(target: target, context: context, c: c)
    }

    let source = [
        cppGeneratedCaseHeader(family: family, case: c, specHash: specHash),
        "#include \"test_runtime.hpp\"",
        context.usesInputs ? cppInputsInclude : "",
        cppStudentInclude,
        cppVariableDecls(sectionVariables: sectionVariables, family: family),
        "int main() {",
        cppIndent(context.declBlock + body),
        "}",
    ]
    .filter { !$0.isEmpty }
    .joined(separator: "\n")

    return cppShellWrapper(
        embeddedSource: source,
        stem: "\(family.id)_\(c.key)",
        optimization: family.kind == .performanceThreshold ? "-O2" : "-O0")
}

/// The 0-point existence guard other kinds depend on. Referencing the
/// function's address fails to compile when the name is absent — reported as
/// a FAILURE (exit 1), not an error: a missing function is the student's to
/// fix, exactly like the other languages' guards.
func renderCppExistenceGuard(family: PatternFamily, specHash: String) -> String {
    let target = family.functionName
    let source = """
        \(cppComment("Generated by Chickadee — existence guard for family '\(family.id)'."))
        \(cppComment("spec_hash: \(specHash)"))
        #include "test_runtime.hpp"
        \(cppStudentInclude)
        int main() {
            (void)sizeof(&\(target));
            ck::passed("\(target) is defined");
        }
        """
    return cppShellWrapper(
        embeddedSource: source,
        stem: "\(family.id)_\(patternExistenceGuardCaseKey)",
        optimization: "-O0",
        compileFailureIsTestFailure: true,
        compileFailureMessage:
            "`\(target)` is not defined (or the submission does not compile)")
}

// MARK: - The shell wrapper

private func cppShellWrapper(
    embeddedSource: String,
    stem: String,
    optimization: String,
    compileFailureIsTestFailure: Bool = false,
    compileFailureMessage: String = ""
) -> String {
    let sourceFile = ".ck_src_\(stem).cpp"
    let binaryFile = ".ck_bin_\(stem)"
    let compileStep: String
    if compileFailureIsTestFailure {
        compileStep = """
            if ! g++ -std=c++20 \(optimization) \(sourceFile) -o \(binaryFile) 1>&2; then
                printf '%s\\n' \(shellSingleQuoted("{\"shortResult\": \"\(compileFailureMessage)\"}"))
                exit 1
            fi
            """
    } else {
        compileStep =
            "g++ -std=c++20 \(optimization) \(sourceFile) -o \(binaryFile) 1>&2 || exit 2"
    }
    return """
        #!/bin/sh
        # Generated by Chickadee — do not edit. The C++ source below is the
        # test; this wrapper locates the submission, compiles one translation
        # unit with the injected runtime, and runs it under the ordinary
        # shell-script contract.
        student_file=""
        if [ -f .chickadee_student_module ]; then
            student_file=$(cat .chickadee_student_module)
        fi
        if [ ! -f "$student_file" ]; then
            for candidate in *.cpp; do
                case "$candidate" in
                    .ck_*|*test_*) ;;
                    *) student_file="$candidate"; break ;;
                esac
            done
        fi
        if [ ! -f "$student_file" ]; then
            echo "No C++ submission file was found to grade." 1>&2
            exit 2
        fi
        cp "$student_file" .ck_solution.cpp
        cat > \(sourceFile) <<'CHICKADEE_GENERATED_SOURCE'
        \(embeddedSource)
        CHICKADEE_GENERATED_SOURCE
        \(compileStep)
        exec ./\(binaryFile)
        """ + "\n"
}

/// The student include, with `main` renamed so a main-bearing submission (an
/// intro "write a program" file) still exposes its functions to the test.
/// The macro renames the token only — string literals and comments are
/// untouched by the preprocessor.
private let cppStudentInclude = """
    #define main ck_student_main
    #include ".ck_solution.cpp"
    #undef main
    """

/// Emitted only when the case references a per-student input.
/// `__has_include` keeps a stale generated test harmless when the inputs
/// file is absent: the reference then fails to compile loudly rather than
/// grading against a missing value.
private let cppInputsInclude = """
    #if __has_include("_ck_inputs.hpp")
    #include "_ck_inputs.hpp"
    #endif
    """

private func cppGeneratedCaseHeader(
    family: PatternFamily, case c: PatternCase, specHash: String
) -> String {
    let label = c.label.isEmpty ? "" : " (\(c.label))"
    return """
        \(cppComment("Generated by Chickadee — pattern family '\(family.id)', case '\(c.key)'\(label)."))
        \(cppComment("Edit the family, not this file. spec_hash: \(specHash)"))
        """
}

/// Section + family variables as file-scope consts. C++ forbids redefining a
/// name in one scope, so the `family > section` shadowing the other languages
/// get from later-assignment-wins is spelled here by emitting the family's
/// value and FILTERING the section duplicate out.
private func cppVariableDecls(
    sectionVariables: [FamilyVariable], family: PatternFamily
) -> String {
    var seen = Set<String>()
    var declarations: [String] = []
    for variable in family.variables + sectionVariables
    where seen.insert(variable.name).inserted {
        declarations.append(
            "inline const auto \(variable.name) = \(variable.value.cppLiteral);")
    }
    return declarations.joined(separator: "\n")
}

// MARK: - Call context

/// The rendered pieces a kind body composes: argument bindings, the call's
/// argument list, and the C++ expression fragment that previews the inputs in
/// a failure message.
private struct CppCallContext {
    let declBlock: String  // "auto x = ...;" lines opening main(), or ""
    let callArgs: String  // "x, y"
    let inputLine: String  // C++ expr: "input: x=..., y=...\n" (or no-input)
    let usesInputs: Bool  // any per-student reference → include _ck_inputs.hpp
    let expectedExpression: String  // per-student ref, variable ref, or literal
}

private func cppCallContext(
    for family: PatternFamily, case c: PatternCase, perStudentNames: Set<String>
) -> CppCallContext {
    let argNames: [String] = {
        if !family.paramNames.isEmpty { return family.paramNames }
        return c.args.indices.map { "arg_\($0 + 1)" }
    }()
    let provided: [Bool] = {
        guard !c.argsProvided.isEmpty else { return Array(repeating: true, count: argNames.count) }
        return (0..<argNames.count).map { i in i < c.argsProvided.count ? c.argsProvided[i] : true }
    }()
    let varRefs: [String?] = {
        guard !c.argVarRefs.isEmpty else { return Array(repeating: nil, count: argNames.count) }
        return (0..<argNames.count).map { i in i < c.argVarRefs.count ? c.argVarRefs[i] : nil }
    }()

    var usesInputs = false
    func reference(_ name: String) -> String {
        if perStudentNames.contains(name) {
            usesInputs = true
            return "ck_inputs::\(name)"
        }
        return name
    }

    var declLines: [String] = []
    var callParts: [String] = []
    var previewParts: [String] = []
    for (idx, name) in argNames.enumerated() {
        guard idx < provided.count ? provided[idx] : true else {
            // C++ has no keyword arguments either: an omission ends the list,
            // and the callee's defaulted parameters take over — the same
            // partial call a student could write themselves.
            break
        }
        if let refName = idx < varRefs.count ? varRefs[idx] : nil {
            declLines.append("auto \(name) = \(reference(refName));")
        } else if idx < c.args.count {
            declLines.append("auto \(name) = \(c.args[idx].cppLiteral);")
        }
        callParts.append(name)
        previewParts.append("\"\(name)=\" + ck::format(\(name))")
    }

    let inputLine: String
    if previewParts.isEmpty {
        inputLine = "\"\(GeneratedMessage.input)(no input)\\n\""
    } else {
        let joined = previewParts.joined(separator: " + \", \" + ")
        inputLine = "\"\(GeneratedMessage.input)\" + \(joined) + \"\\n\""
    }

    // The expected value resolves with the same reference rules as the
    // arguments: a per-student name → ck_inputs::, another name → the
    // file-scope variable, no reference → the rendered literal.
    let expectedExpression: String
    if let ref = c.expectedVarRef {
        expectedExpression = reference(ref)
    } else {
        expectedExpression = c.expected.cppLiteral
    }

    return CppCallContext(
        declBlock: declLines.isEmpty ? "" : declLines.joined(separator: "\n") + "\n",
        callArgs: callParts.joined(separator: ", "),
        inputLine: inputLine,
        usesInputs: usesInputs,
        expectedExpression: expectedExpression
    )
}

// MARK: - Kind bodies

private func cppEqualityBody(
    target: String, context: CppCallContext, c: PatternCase, unordered: Bool
) -> String {
    let compare = unordered ? "ck::unordered_equal" : "ck::equal"
    let mismatch = unordered ? GeneratedMessage.wrongElements : GeneratedMessage.wrongValue
    return cppGuarded(
        """
        auto expected = \(context.expectedExpression);
        auto result = \(target)(\(context.callArgs));
        if (!\(compare)(result, expected)) {
            ck::failed(std::string("\(mismatch)\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.expected)" + ck::format(expected) + "\\n"
                + "\(GeneratedMessage.got)" + ck::format(result));
        }
        ck::passed("\(GeneratedMessage.returned)" + ck::format(result));
        """, inputLine: context.inputLine)
}

private func cppApproximateBody(
    target: String, context: CppCallContext, c: PatternCase, family: PatternFamily
) -> String {
    let tolerance = family.defaults.tolerance ?? 1e-6
    return cppGuarded(
        """
        auto expected = \(context.expectedExpression);
        auto result = \(target)(\(context.callArgs));
        if (!ck::close(result, expected, \(tolerance))) {
            ck::failed(std::string("\(GeneratedMessage.outsideTolerance)\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.expected)" + ck::format(expected) + " (±\(tolerance))\\n"
                + "\(GeneratedMessage.got)" + ck::format(result));
        }
        ck::passed("\(GeneratedMessage.returned)" + ck::format(result) + " (within ±\(tolerance))");
        """, inputLine: context.inputLine)
}

private func cppVariableEqualityBody(
    family: PatternFamily, context: CppCallContext, c: PatternCase
) -> String {
    // The "function name" IS the variable name for this kind — a global in
    // the student's file, in scope through the single-TU include. Referencing
    // it is the existence check: missing → the wrapper's exit-2 diagnostic
    // names it.
    let variable = family.functionName
    return """
        auto expected = \(context.expectedExpression);
        if (!ck::equal(\(variable), expected)) {
            ck::failed(std::string("Variable `\(variable)` has the \(GeneratedMessage.wrongValue)\\n")
                + "\(GeneratedMessage.expected)" + ck::format(expected) + "\\n"
                + "\(GeneratedMessage.got)" + ck::format(\(variable)));
        }
        ck::passed("\(variable) is " + ck::format(\(variable)));
        """
}

private func cppReturnTypeBody(
    target: String, context: CppCallContext, c: PatternCase
) -> String {
    let expectedType: String = {
        if case .string(let s) = c.expected { return s }
        return "int"
    }()
    return cppGuarded(
        """
        auto result = \(target)(\(context.callArgs));
        if (!ck::type_matches<decltype(result)>("\(expectedType)")) {
            ck::failed(std::string("\(GeneratedMessage.wrongReturnType)\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.expected)\(expectedType)\\n"
                + "\(GeneratedMessage.got)" + ck::type_name<decltype(result)>());
        }
        ck::passed("\(GeneratedMessage.returned)a \(expectedType)");
        """, inputLine: context.inputLine)
}

private func cppExceptionBody(
    target: String, context: CppCallContext, c: PatternCase
) -> String {
    let substring: String = {
        if case .string(let s) = c.expected { return s }
        return ""
    }()
    return """
        std::string what;
        auto outcome = ck::expect_throw(
            [&] { (void)\(target)(\(context.callArgs)); }, "\(substring)", what);
        if (outcome == ck::ThrowOutcome::returned) {
            ck::failed(std::string("no error raised\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.expected)an exception\(substring.isEmpty ? "" : " matching \\\"\(substring)\\\"")");
        }
        if (outcome == ck::ThrowOutcome::threwOther) {
            ck::failed(std::string("wrong error raised\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.expected)an exception matching \\"\(substring)\\"\\n"
                + "\(GeneratedMessage.got)" + what);
        }
        ck::passed("Raised as expected: " + what);
        """
}

private func cppPerformanceBody(
    target: String, context: CppCallContext, c: PatternCase
) -> String {
    // The budget is authored in MILLISECONDS, like every other renderer.
    let budgetMs: String = {
        switch c.expected {
        case .int(let i): return String(Double(i))
        case .double(let d): return String(d)
        default: return "1000.0"
        }
    }()
    return cppGuarded(
        """
        auto ck_started = std::chrono::steady_clock::now();
        auto result = \(target)(\(context.callArgs));
        double ck_elapsed_ms = std::chrono::duration<double, std::milli>(
            std::chrono::steady_clock::now() - ck_started).count();
        (void)result;
        if (ck_elapsed_ms > \(budgetMs)) {
            ck::failed(std::string("too slow\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.threshold)" + ck::format(\(budgetMs)) + " ms\\n"
                + "\(GeneratedMessage.elapsed)" + ck::format(ck_elapsed_ms) + " ms");
        }
        ck::passed("Completed in " + ck::format(ck_elapsed_ms) + " ms");
        """, inputLine: context.inputLine)
}

private func cppStdoutBody(
    target: String, context: CppCallContext, c: PatternCase
) -> String {
    cppGuarded(
        """
        auto expected = \(context.expectedExpression);
        ck::CaptureStdout ck_capture;
        (void)\(target)(\(context.callArgs));
        auto ck_printed = ck_capture.finish();
        // Trailing-newline tolerance, matching the other stdout renderers.
        while (!ck_printed.empty() && (ck_printed.back() == '\\n' || ck_printed.back() == '\\r')) {
            ck_printed.pop_back();
        }
        std::string ck_wanted(expected);
        while (!ck_wanted.empty() && (ck_wanted.back() == '\\n' || ck_wanted.back() == '\\r')) {
            ck_wanted.pop_back();
        }
        if (ck_printed != ck_wanted) {
            ck::failed(std::string("\(GeneratedMessage.wrongOutput)\\n")
                + \(context.inputLine)
                + "\(GeneratedMessage.expected)" + ck::format(ck_wanted) + "\\n"
                + "\(GeneratedMessage.got)" + ck::format(ck_printed));
        }
        ck::passed("Printed the expected output");
        """, inputLine: context.inputLine)
}

/// Wraps a body in the shared unexpected-exception handler: a throw from
/// the student's code is a graded FAIL with the same first line every other
/// language uses, never a std::terminate.
private func cppGuarded(_ inner: String, inputLine: String) -> String {
    """
    try {
    \(cppIndent(inner))
    } catch (const std::exception& ck_e) {
        ck::failed(std::string("\(GeneratedMessage.unexpectedException)\\n")
            + \(inputLine)
            + "\(GeneratedMessage.error)" + ck_e.what());
    }
    """
}

// MARK: - Small utilities

private func cppIndent(_ block: String) -> String {
    block.split(separator: "\n", omittingEmptySubsequences: false)
        .map { $0.isEmpty ? "" : "    \($0)" }
        .joined(separator: "\n")
}
