#!/usr/bin/env bash
#
# Build the RunnerCore wasm bridge (wasm/ sub-package) and vendor a
# self-contained, no-CDN browser artifact under Public/runner-wasm/.
#
# RunnerCore is the substrate-free grading logic shared with the native worker.
# This compiles it (plus the BridgeJS bridge in wasm/Sources/RunnerWasm/) to
# wasm with the EMBEDDED Swift SDK — a
# ~270 KB artifact (~130 KB gzipped), far smaller than the standard wasm
# runtime — so the browser runner can call the SAME extraction code instead of
# a hand-written JS copy.
#
# Prerequisites (one-time, see docs/runner-wasm-migration.md):
#   * Swift toolchain matching the wasm SDK (6.4.0 — pinned by the swiftly
#     version in .github/workflows/runner-wasm-vendor.yml)
#   * The Embedded Swift WebAssembly SDK installed and named via SWIFT_WASM_SDK
#     (defaults to swift-6.4.0-RELEASE_wasm-embedded).
#   * Node + npx (for esbuild) to bundle the WASI shim locally (no CDN: FIPPA).
#
# Output (checked in, like Public/pyodide / Public/vendor — CI and contributors
# need no wasm SDK; rebuild only when RunnerCore or the bridge changes):
#   Public/runner-wasm/runner-core.js   — self-contained ESM loader (init/exports)
#   Public/runner-wasm/RunnerWasm.wasm  — the embedded wasm module
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
sdk="${SWIFT_WASM_SDK:-swift-6.4.0-RELEASE_wasm-embedded}"
out_dir="$repo_root/Public/runner-wasm"

cd "$repo_root/wasm"

# NOTE: do NOT set JAVASCRIPTKIT_EXPERIMENTAL_EMBEDDED_WASM here. The embedded
# wasm SDK already forces Embedded mode globally, so JavaScriptKit +
# JavaScriptEventLoop compile embedded without it — and setting it flips the
# PackageToJS output from the required WASI *reactor* model (exported
# `_initialize`) to a *command* (`_start`), which JavaScriptKit's runtime
# rejects ("supports only WASI reactor ABI").

pkg=".build/plugins/PackageToJS/outputs/Package"

# Start from empty plugin output directories. PackageToJS refreshes the files
# it writes but never removes ones it no longer would, and it bundles BridgeJS
# glue whenever it finds some under `.build/plugins/outputs` — so a
# `bridge-js.js` left over from a BridgeJS trial build rides into `index.js`,
# and esbuild below bundles whatever `index.js` imports. A stale file therefore
# ships inside the vendored loader without a warning, which is how one
# experiment's glue added 23 KB to `runner-core.js` before these lines existed.
rm -rf "$pkg" .build/plugins/outputs

echo "Building RunnerWasm (Embedded Swift, SDK: $sdk)…"
swift package --swift-sdk "$sdk" js -c release

echo "Bundling a self-contained, no-CDN browser ESM with esbuild…"
( cd "$pkg" && npm install --silent )

rm -rf "$out_dir"
mkdir -p "$out_dir"
# The bundle's entry is the checked-in loader, not the plugin's index.js: it
# re-exports the plugin's init() and registers the legacy `globalThis.runner*`
# adapters over the typed BridgeJS exports (see wasm/loader/runner-core-entry.js).
npx --yes esbuild loader/runner-core-entry.js --bundle --format=esm --outfile="$out_dir/runner-core.js"

# Vendor the generated TypeScript declaration beside the loader: it is the
# bridge's contract (every export, every struct field), regenerated by the
# BridgeJS plugin on each build, and the file a consumer reads instead of the
# Swift. Served like the loader (must-revalidate); ~1 KB.
cp "$pkg/bridge-js.d.ts" "$out_dir/runner-core.d.ts"

unopt_size=$(wc -c < "$pkg/RunnerWasm.wasm")

# Optimize for size — this is a browser-delivered artifact, so -Oz (size) over
# -O (speed). wasm-opt ships with binaryen; run it via npx so no system install
# is needed (same mechanism as esbuild above). If it's unavailable (offline),
# fall back to the unoptimized module with a warning — the build still produces
# a correct, working artifact.
#
# --strip-debug is load-bearing, and the reason is worth keeping. The release
# build links with `-g`, so the module the PackageToJS plugin hands over
# carries full DWARF (.debug_info, .debug_names, .debug_str, .debug_line, …).
# The plugin's own "Stripping DWARF debug info…" step runs THROUGH wasm-opt,
# which it looks up on PATH — and on a CI runner there is none, so it warns and
# copies the module unstripped, DWARF and all. This script then ran wasm-opt
# via npx, which keeps unknown custom sections unless told otherwise. Result:
# for every re-vendor before this flag, ~1.2 MB of the ~1.5 MB artifact
# (~360 KB of the ~490 KB gzipped) was debug data no browser reads. Measured:
# the same module strips to ~270 KB raw / ~130 KB gzip with byte-identical
# grading output (the Node output-contract harness runs against it).
opt_wasm="$out_dir/.RunnerWasm.opt.wasm"
if npx --yes wasm-opt --version >/dev/null 2>&1; then
    echo "Optimizing with wasm-opt -Oz --converge --strip-debug --strip-producers…"
    # --converge: re-run passes to fixpoint for a little extra size.
    # --strip-debug: drop the DWARF sections and the name section (see above).
    # --strip-producers: drop the toolchain "producers" metadata section (the
    # exported grading functions the JS loader calls are unaffected).
    npx --yes wasm-opt -Oz --converge --strip-debug --strip-producers \
        "$pkg/RunnerWasm.wasm" -o "$opt_wasm"
else
    echo "WARNING: wasm-opt unavailable — vendoring the UNOPTIMIZED, UNSTRIPPED module."
    echo "         Expect a ~1.7 MB artifact (~620 KB gzip) that fails the size ceiling."
    cp "$pkg/RunnerWasm.wasm" "$opt_wasm"
fi
opt_size=$(wc -c < "$opt_wasm")

# Content-hash the filename so the artifact can be cached immutably: new bytes →
# new filename → clean cache bust; unchanged bytes → identical filename → served
# from cache effectively forever (see RunnerWasmCacheMiddleware).
hash=$(shasum -a 256 "$opt_wasm" | cut -c1-12)
wasm_name="RunnerWasm.${hash}.wasm"
mv "$opt_wasm" "$out_dir/$wasm_name"

# Point the generated loader at the hashed filename (it fetches
# `new URL("RunnerWasm.wasm", import.meta.url)`). The loader keeps its stable
# name and is served must-revalidate, so it always resolves to the current hash.
sed -i.bak "s/RunnerWasm\.wasm/${wasm_name}/g" "$out_dir/runner-core.js"
rm -f "$out_dir/runner-core.js.bak"

gzip_size=$(gzip -9 -c "$out_dir/$wasm_name" | wc -c)
if command -v brotli >/dev/null 2>&1; then
    brotli_size="$(brotli -q 11 -c "$out_dir/$wasm_name" | wc -c) bytes"
else
    brotli_size="(brotli not installed — install binaryen/brotli to measure)"
fi

echo "Done. Vendored:"
echo "  $out_dir/runner-core.js        ($(wc -c < "$out_dir/runner-core.js") bytes, loader)"
echo "  $out_dir/runner-core.d.ts      (typed contract, generated by BridgeJS)"
echo "  $out_dir/$wasm_name  (content-hashed)"
echo ""
echo "Wasm size:"
echo "  unoptimized:  ${unopt_size} bytes"
echo "  wasm-opt -Oz: ${opt_size} bytes"
echo "  gzip -9:      ${gzip_size} bytes"
echo "  brotli -q11:  ${brotli_size}"
echo ""
echo "Size budget:"
"$repo_root/scripts/check-runner-wasm-size.sh" || true
