#!/usr/bin/env bash
#
# Refreshes the vendored browser libraries served from Public/vendor/.
#
#   jszip.min.js             — jszip $JSZIP_VERSION, fetched from the CDN
#   codemirror.js            — bundled ESM, see Tools/vendor/codemirror-entry.js
#   iframe-commands-host.js  — parent-frame half of the JupyterLite command bridge
#   xeus-bootstrap.js        — mambajs slice the grading workers unpack envs with
#   xeus-unpack.wasm         — untarjs unpacker that bootstrap drives
#
# Public/vendor is checked in. Every contributor and every CI runner gets the
# same bytes with no network fetch at build time, and no student or instructor
# IP reaches cdn.jsdelivr.net or esm.sh on page load — the FIPPA/PIPEDA concern
# from the v0.4.171 audit.
#
# INPUT VERSIONS COME FROM Tools/vendor/package-lock.json, except jszip, which
# is fetched from the CDN at the version pinned below rather than bundled. Bump
# a pin, rerun this script, and commit the regenerated bytes IN THE SAME
# COMMIT — a bump on its own changes nothing that is served.
#
# Rerun after `scripts/build-jupyterlite.sh` when the kernels have been
# re-vendored, so the bridge halves stay matched.

set -euo pipefail

JSZIP_VERSION="3.10.2"

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

public_vendor="$repo_root/Public/vendor"

# ── jszip ─────────────────────────────────────────────────────────────
echo "==> Fetching jszip $JSZIP_VERSION"
mkdir -p "$public_vendor"
curl -fsSL \
    "https://cdn.jsdelivr.net/npm/jszip@${JSZIP_VERSION}/dist/jszip.min.js" \
    -o "$public_vendor/jszip.min.js"

# ── CodeMirror bundle ─────────────────────────────────────────────────
echo "==> Bundling CodeMirror via npm + esbuild"
cd "$repo_root/Tools/vendor"
npm install --silent --no-audit --no-fund
npx esbuild codemirror-entry.js \
    --bundle \
    --format=esm \
    --target=es2020 \
    --minify \
    --outfile="$public_vendor/codemirror.js"

# ── jupyter-iframe-commands host bridge ───────────────────────────────
# The parent-frame half of the iframe command bridge (comlink folded in).
# Pairs with the `jupyter-iframe-commands` labextension federated into the
# JupyterLite bundle (Tools/jupyterlite/requirements.txt).
echo "==> Bundling jupyter-iframe-commands host bridge via esbuild"
npx esbuild iframe-commands-host-entry.js \
    --bundle \
    --format=esm \
    --target=es2020 \
    --minify \
    --outfile="$public_vendor/iframe-commands-host.js"

# ── xeus kernel bootstrap (browser-graded R) ──────────────────────────
# The mambajs slice Public/r-grading-worker.js uses to unpack the vendored
# `chickadee-r` conda env into the kernel's emscripten filesystem. IIFE, not
# ESM: the grading worker is a classic worker (it needs importScripts for the
# kernel's emscripten glue). See Tools/vendor/xeus-bootstrap-entry.mjs for why
# this is built from npm source instead of reusing the federated
# @jupyterlite/xeus-extension chunks.
#
# untarjs ships its unpacking wasm as a bundler-resolved `import ... from
# './unpack.wasm'`. That default is only consulted when no locateWasm is
# supplied, and r-grading-worker.js always supplies one — so the import is
# dropped (--loader:.wasm=empty) and the wasm is vended explicitly instead,
# under a name that says which subsystem owns it.
echo "==> Bundling xeus kernel bootstrap via esbuild"
npx esbuild xeus-bootstrap-entry.mjs \
    --bundle \
    --format=iife \
    --target=es2020 \
    --minify \
    --loader:.wasm=empty \
    --outfile="$public_vendor/xeus-bootstrap.js"
cp node_modules/@emscripten-forge/untarjs/lib/unpack.wasm \
   "$public_vendor/xeus-unpack.wasm"

echo "==> Vendor refresh complete."
echo "    Public/vendor/jszip.min.js   $(du -sh "$public_vendor/jszip.min.js" | cut -f1)"
echo "    Public/vendor/codemirror.js  $(du -sh "$public_vendor/codemirror.js" | cut -f1)"
echo "    Public/vendor/xeus-bootstrap.js $(du -sh "$public_vendor/xeus-bootstrap.js" | cut -f1)"
