// Tests/APITests/GeneratedMessageVocabularyTests.swift
//
// Two guards on the shared failure-message vocabulary.
//
// 1. The labels still render exactly the bytes they used to. `GeneratedMessage`
//    COMPUTES its padding from the widest label in each message rather than
//    storing a flat list of constants, which is what stops a new field from
//    being mis-padded — but it also means a change to a group's membership
//    silently re-pads every label in it. The goldens would catch that for the
//    kinds they cover; this catches it directly, and names the label.
//
// 2. No renderer has gone back to hand-typing one. The vocabulary was hoisted
//    out of FOURTEEN files; a hoist that only holds until the next person types
//    `"  expected: "` again is worth very little, and "half the call sites read
//    the shared constant and half do not" is worse than none, because the next
//    reader assumes it is all shared.
//
// The second guard DISCOVERS the files it checks with a glob instead of listing
// them. A hardcoded list is the "enumerated rather than discovered, fails open"
// shape this codebase has been bitten by three times (the `chickadee-*` glob in
// build-jupyterlite.sh, `expected_language` in check-xeus-vendored.sh, and a
// conformance test that read `arguments: [.python, .r]` while looking like a
// matrix) — a new renderer file would simply not be checked.

import Foundation
import Testing

@testable import APIServer

@Suite struct GeneratedMessageVocabularyTests {

    /// The exact bytes each label has always rendered. Written out longhand on
    /// purpose: this is the assertion, so deriving it the way the source does
    /// would make it agree with any bug.
    static let expectedLabels: [(String, String)] = [
        ("input", "  input:    "),
        ("expected", "  expected: "),
        ("got", "  got:      "),
        ("error", "  error:    "),
        ("source", "  source:   "),
        ("delta", "  delta:    "),
        ("hint", "  hint:     "),
        ("row", "  row:      "),
        ("missing", "  missing:  "),
        ("budget", "  budget:   "),
        ("took", "  took:     "),
    ]

    @Test func standardLabelsRenderTheirHistoricalBytes() {
        for (name, expected) in Self.expectedLabels {
            #expect(
                GeneratedMessage.standard.label(name) == expected,
                """
                The `\(name)` label renders \(GeneratedMessage.standard.label(name).debugDescription) \
                but every generated script on disk carries \(expected.debugDescription). A label was \
                added to `GeneratedMessage.standard` that is longer than `expected`, which re-pads \
                the whole group — and the generated bytes feed `spec_hash` and the `TestSetupCache` \
                key, so re-padding rewrites every existing assignment's manifest.
                """)
        }
    }

    /// The three messages that carry a label longer than `expected:` and so sit
    /// on a wider column of their own.
    @Test func widerMessagesKeepTheirOwnColumns() {
        #expect(GeneratedMessage.threshold == "  threshold: ")
        #expect(GeneratedMessage.elapsed == "  elapsed:   ")
        #expect(GeneratedMessage.performanceError == "  error:     ")

        #expect(GeneratedMessage.expectedSubset == "  expected (subset): ")
        #expect(GeneratedMessage.gotSubset == "  got:               ")
        #expect(GeneratedMessage.missingSubset == "  missing:           ")

        #expect(GeneratedMessage.expectedColumns == "  expected columns: ")
        #expect(GeneratedMessage.gotColumns == "  got:              ")

        #expect(GeneratedMessage.expectedAtLeast == "  expected at least: ")
        #expect(GeneratedMessage.gotAtLeast == "  got:               ")
    }

    /// Every label in a group lines up: that is the entire reason the group
    /// computes its width instead of storing constants.
    @Test func everyGroupIsInternallyAligned() {
        let groups: [(String, [String])] = [
            ("standard", Self.expectedLabels.map(\.1)),
            (
                "performance",
                [GeneratedMessage.threshold, GeneratedMessage.elapsed, GeneratedMessage.performanceError]
            ),
            (
                "subsetColumns",
                [GeneratedMessage.expectedSubset, GeneratedMessage.gotSubset, GeneratedMessage.missingSubset]
            ),
            ("dataFrameColumns", [GeneratedMessage.expectedColumns, GeneratedMessage.gotColumns]),
            ("atLeast", [GeneratedMessage.expectedAtLeast, GeneratedMessage.gotAtLeast]),
        ]
        for (name, labels) in groups {
            let widths = Set(labels.map(\.count))
            #expect(widths.count == 1, "\(name) labels do not share a column: \(widths.sorted())")
        }
    }

    // MARK: - No renderer hand-types a label again

    /// Source files that emit generated student-facing scripts, found rather
    /// than listed, so a new renderer is covered the day it lands.
    static func rendererSources() throws -> [URL] {
        let dir = LanguageConformanceMatrixTests.repoRoot
            .appendingPathComponent("Sources/APIServer/Utilities")
        let all = try FileManager.default.contentsOfDirectory(at: dir, includingPropertiesForKeys: nil)
        return
            all
            .filter { $0.pathExtension == "swift" }
            .filter { $0.lastPathComponent.contains("Renderer") || $0.lastPathComponent.contains("Template") }
            .filter { $0.lastPathComponent != "GeneratedMessageVocabulary.swift" }
            .sorted { $0.lastPathComponent < $1.lastPathComponent }
    }

    @Test func theGlobFindsTheRenderersItIsSupposedTo() throws {
        let names = try Self.rendererSources().map(\.lastPathComponent)
        // Not an exhaustive list — a lower bound, so an empty or badly-scoped
        // glob cannot make the drift guard below pass by checking nothing.
        #expect(names.count >= 14, "the renderer glob found only \(names.count) files: \(names)")
        for required in [
            "PatternFamilyRendererR.swift", "NotebookCheckRendererR.swift",
            "PatternFamilyRenderer+BoundaryEquality.swift", "TestScriptTemplates.swift",
        ] {
            #expect(names.contains(required), "the renderer glob missed \(required)")
        }
    }

    @Test func noRendererHandTypesAFieldLabel() throws {
        // Built from the vocabulary, so it tracks whatever the labels become.
        let labels =
            Self.expectedLabels.map(\.1) + [
                GeneratedMessage.threshold, GeneratedMessage.elapsed,
                GeneratedMessage.expectedSubset, GeneratedMessage.expectedColumns,
                GeneratedMessage.expectedAtLeast,
            ]

        for url in try Self.rendererSources() {
            let source = try String(contentsOf: url, encoding: .utf8)
            for (offset, line) in source.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
                // Prose about a label is not a label. The lesson from the Leaf
                // comment finding (CLAUDE.md): a scanner that cannot tell markup
                // from prose about markup flags its own documentation.
                if line.trimmingCharacters(in: .whitespaces).hasPrefix("//") { continue }
                for label in labels where line.contains(label) {
                    Issue.record(
                        """
                        \(url.lastPathComponent):\(offset + 1) hand-types the field label \
                        \(label.debugDescription). Interpolate the matching `GeneratedMessage` \
                        constant instead — the point of the vocabulary is that a new language \
                        inherits this wording rather than retyping it, and a retyped copy is \
                        exactly how Python and R drifted apart in the first place.
                        """)
                }
            }
        }
    }
}
