// Tests/APITests/GeneratedSourceGoldenTests.swift
//
// Byte-for-byte snapshots of every generated script, for every kind, in every
// language. Their job is not to say the output is *right* — the renderer tests
// and the conformance matrix do that — but to say it has not CHANGED.
//
// WHY BYTES, AND NOT "LOOKS EQUIVALENT". Generated filenames embed a
// `spec_hash`, and `TestSetupCache` keys on manifest + zip content. So a
// renderer edit that changes one byte of Python or R output rewrites every
// existing assignment's manifest and busts every cache entry. That makes the
// blast radius of an "obviously harmless" refactor much larger than it looks.
//
// It also makes the planned refactor PROVABLE. Extracting the 17 semantic kinds
// onto a shared emission vocabulary — so a new language supplies ~12 primitives
// instead of ~1,200 lines — is a large change to code that generates
// student-facing tests. With these goldens it is not a judgement call: snapshot
// first, refactor, and the work is correct exactly when these still pass. No
// "looks the same to me" step.
//
// UPDATING. When output changes on purpose:
//
//     CHICKADEE_UPDATE_GOLDENS=1 swift test --filter GeneratedSourceGoldenTests
//
// then READ THE DIFF. A regenerated golden is a claim that every existing
// assignment's generated bytes should change; the diff is the only place that
// claim is visible.

import Core
import Foundation
import Testing

@testable import APIServer

@Suite(.serialized) struct GeneratedSourceGoldenTests {

    static var goldenRoot: URL {
        var url = URL(fileURLWithPath: #filePath)  // .../Tests/APITests/<this>
        for _ in 0..<2 { url.deleteLastPathComponent() }  // -> Tests/
        return url.appendingPathComponent("Fixtures/generated-source")
    }

    static var isUpdating: Bool {
        ProcessInfo.processInfo.environment["CHICKADEE_UPDATE_GOLDENS"] == "1"
    }

    /// Compare `actual` against the stored golden at `relativePath`, or write it
    /// when updating. Missing goldens fail rather than silently passing — a new
    /// kind or language must be snapshotted deliberately, which is the same
    /// fail-closed rule the conformance matrix follows.
    static func assertGolden(_ actual: String, at relativePath: String) throws {
        let url = goldenRoot.appendingPathComponent(relativePath)
        if isUpdating {
            try FileManager.default.createDirectory(
                at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
            try actual.write(to: url, atomically: true, encoding: .utf8)
            return
        }
        guard let expected = try? String(contentsOf: url, encoding: .utf8) else {
            Issue.record(
                """
                No golden for \(relativePath). If this kind/language is new, create it with \
                CHICKADEE_UPDATE_GOLDENS=1 swift test --filter GeneratedSourceGoldenTests \
                and review the result.
                """)
            return
        }
        #expect(
            actual == expected,
            """
            Generated source for \(relativePath) changed.

            This is not cosmetic: generated filenames embed a spec_hash and \
            TestSetupCache keys on manifest content, so changed bytes rewrite \
            every existing assignment's manifest and bust every cache entry.

            If the change is intended, regenerate with CHICKADEE_UPDATE_GOLDENS=1 \
            and review the diff.
            """)
    }

    // MARK: - Pattern families

    @Test(arguments: AssignmentLanguage.allCases)
    func patternFamilySourceIsUnchanged(_ language: AssignmentLanguage) throws {
        for kind in GeneratedSourceFixtures.orderedPatternKinds {
            let scripts = renderPatternFamily(
                GeneratedSourceFixtures.family(kind: kind), language: language)
            // The filenames are part of the contract (they carry the spec_hash
            // into the manifest), so snapshot them alongside the source rather
            // than only the bodies.
            let manifestOfScripts =
                scripts
                .map { "\($0.filename)\ttier=\($0.tier.rawValue)\tpoints=\($0.points)" }
                .joined(separator: "\n")
            try Self.assertGolden(
                manifestOfScripts + "\n",
                at: "\(language.rawValue)/pattern/\(kind.rawValue).manifest")

            for script in scripts {
                try Self.assertGolden(
                    script.source,
                    at: "\(language.rawValue)/pattern/\(kind.rawValue)/\(script.filename)")
            }
        }
    }

    // MARK: - Notebook checks

    @Test(arguments: AssignmentLanguage.allCases)
    func notebookCheckSourceIsUnchanged(_ language: AssignmentLanguage) throws {
        for kind in GeneratedSourceFixtures.supportedCheckKinds(for: language) {
            let generated = renderNotebookCheck(
                GeneratedSourceFixtures.check(kind: kind), language: language)
            try Self.assertGolden(
                "\(generated.script.filename)\ttier=\(generated.script.tier.rawValue)\n",
                at: "\(language.rawValue)/check/\(kind.rawValue).manifest")
            try Self.assertGolden(
                generated.script.source,
                at: "\(language.rawValue)/check/\(kind.rawValue)/\(generated.script.filename)")
        }
    }

    // MARK: - The inputs file

    /// Small, but it is the file a per-student assignment depends on and it has
    /// no other byte-level cover.
    @Test(arguments: AssignmentLanguage.allCases)
    func inputsFileSourceIsUnchanged(_ language: AssignmentLanguage) throws {
        let rendered = language.renderInputsFile([
            "threshold": language.literal(.int(42)),
            "label": language.literal(.string("high")),
            "weights": language.literal(.array([.double(0.5), .double(1.5)])),
        ])
        try Self.assertGolden(rendered, at: "\(language.rawValue)/\(language.inputsFileName)")
    }

    /// Guards the guard: a golden suite that silently snapshots nothing would
    /// pass forever. Every language must contribute at least one stored file.
    @Test func everyLanguageHasStoredGoldens() throws {
        for language in AssignmentLanguage.allCases {
            let dir = Self.goldenRoot.appendingPathComponent(language.rawValue)
            let contents = try? FileManager.default.subpathsOfDirectory(atPath: dir.path)
            #expect(
                (contents?.count ?? 0) > 0,
                "no goldens stored for \(language) — regenerate with CHICKADEE_UPDATE_GOLDENS=1")
        }
    }
}
