// Tests/APITests/PatternFamilyRendererRTests.swift
//
// Coverage for the R pattern-family renderer. Two layers:
//
//   1. Byte-shape assertions — CI-safe, no interpreter needed: the `.R`
//      extension, the runtime `source()`, R literals, and that Python's
//      generated bytes are untouched (they feed `spec_hash` /
//      `TestSetupCache` keys and must never move).
//   2. A real `Rscript` execution of every kind, against a correct stub and a
//      wrong one, asserting the generated test passes and fails respectively.
//      Silently skipped where `Rscript` is absent; runs in the r-base
//      container and locally.

import Foundation
import Testing

@testable import APIServer
@testable import Core

@Suite struct PatternFamilyRendererRShapeTests {

    private func family(
        kind: PatternKind, cases: [PatternCase], paramNames: [String] = ["x"],
        functionName: String = "f", defaults: PatternDefaults = PatternDefaults()
    ) -> PatternFamily {
        PatternFamily(
            id: "fam", name: "Fam", kind: kind, functionName: functionName,
            paramNames: paramNames, defaults: defaults, cases: cases)
    }

    private func onlyCase(_ args: [JSONValue], expected: JSONValue) -> PatternCase {
        PatternCase(key: "01", label: "Case 1", args: args, expected: expected)
    }

    @Test func rCasesGetRExtensionAndSourceTheRuntime() throws {
        let fam = family(
            kind: .boundaryEquality, cases: [onlyCase([.int(2)], expected: .int(4))])
        let scripts = renderPatternFamily(fam, language: .r)
        let script = try #require(scripts.first)

        #expect(script.filename == "publictest_fam_01.R")
        #expect(script.source.contains("source(\"test_runtime.R\")"))
        #expect(script.source.contains("chickadee_load_student()"))
        #expect(script.source.contains("chickadee_require_fn(student, \"f\")"))
        // R literal, not Python's.
        #expect(script.source.contains("expected <- 4"))
    }

    @Test func rRendersRLiteralsForCollections() throws {
        let fam = family(
            kind: .boundaryEquality,
            cases: [
                onlyCase([.array([.string("a"), .string("b")])], expected: .array([.int(1), .int(2)]))
            ])
        let source = try #require(renderPatternFamily(fam, language: .r).first).source
        #expect(source.contains("c(\"a\", \"b\")"))
        #expect(source.contains("expected <- c(1, 2)"))
        #expect(!source.contains("['a', 'b']"), "must not emit a Python list")
    }

    @Test func rExistenceGuardUsesRAndFailsNotErrors() throws {
        let fam = family(
            kind: .boundaryEquality, cases: [onlyCase([.int(1)], expected: .int(1))])
        let guardScript = try #require(existenceGuard(for: fam, language: .r))
        #expect(guardScript.filename == "publictest_fam_exists.R")
        #expect(guardScript.points == 0)
        // failed(), not errored() — matches the Python guard so the runner's
        // dependency gate behaves identically in both languages.
        #expect(guardScript.source.contains("failed("))
        #expect(guardScript.source.contains("is not a function"))
    }

    @Test func rPerStudentRefsReadFromChickadeeInputs() throws {
        let c = PatternCase(
            key: "01", label: "Case 1", args: [.null], expected: .null,
            argVarRefs: ["sample1_reads"], expectedVarRef: "human_label")
        let fam = family(kind: .boundaryEquality, cases: [c], paramNames: ["reads"])
        let source = try #require(
            renderPatternFamily(
                fam, perStudentNames: ["sample1_reads", "human_label"], language: .r
            ).first
        ).source
        #expect(source.contains("chickadee_inputs()"))
        #expect(source.contains("\"sample1_reads\""))
        #expect(source.contains("expected <- human_label"))
        #expect(source.contains("is unavailable"), "must fail closed when a value is missing")
    }

    /// The whole point of keeping R in its own renderer: Python output must be
    /// bit-for-bit what it always was.
    @Test func pythonOutputIsUnchangedByDefault() throws {
        let fam = family(
            kind: .boundaryEquality, cases: [onlyCase([.int(2)], expected: .int(4))])
        let defaultScripts = renderPatternFamily(fam)
        let explicitPython = renderPatternFamily(fam, language: .python)
        #expect(defaultScripts == explicitPython)

        let script = try #require(defaultScripts.first)
        #expect(script.filename == "publictest_fam_01.py")
        #expect(script.source.contains("student_module.f("))
        #expect(!script.source.contains("chickadee_load_student"))
    }

    @Test func nonSyntacticNamesAreBacktickQuoted() {
        #expect(rIdentifier("weight_kg") == "weight_kg")
        #expect(rIdentifier("my.var") == "my.var")
        #expect(rIdentifier("2bad") == "`2bad`")
        #expect(rIdentifier("has space") == "`has space`")
    }

    /// Literal globals must reach a hand-authored `.R` test, the way they
    /// already reach a hand-authored `.py` one — the script's extension names
    /// its language.
    @Test func literalGlobalsInlineIntoRawScriptsPerLanguage() {
        let manifest = TestProperties(
            requiredFiles: [], testSuites: [], timeLimitSeconds: 10,
            globalVariables: [
                FamilyVariable(name: "threshold", value: .double(18.5)),
                FamilyVariable(name: "labels", value: .array([.string("lo"), .string("hi")])),
            ])

        let rScript = TestScriptVariablePrepender.applyForRawScript(
            filename: "publictest_x.R", content: "cat(threshold)\n", manifest: manifest)
        #expect(rScript.contains("threshold <- 18.5"))
        #expect(rScript.contains("labels <- c(\"lo\", \"hi\")"))
        #expect(!rScript.contains("threshold = 18.5"), "must not emit Python assignment syntax")

        let pyScript = TestScriptVariablePrepender.applyForRawScript(
            filename: "publictest_x.py", content: "print(threshold)\n", manifest: manifest)
        #expect(pyScript.contains("threshold = 18.5"))
        #expect(pyScript.contains("labels = ["), "a Python list, not R's c(...)")
        #expect(!pyScript.contains("c(\"lo\""))

        // A shell script has no literal syntax to inline into.
        let shScript = TestScriptVariablePrepender.applyForRawScript(
            filename: "publictest_x.sh", content: "echo hi\n", manifest: manifest)
        #expect(shScript == "echo hi\n")
    }
}

/// Executes each rendered R kind for real. `runKind` writes the canonical
/// runtime, a stub submission and the generated script into a temp dir, runs
/// `Rscript`, and returns the exit code (0 pass / 1 fail / 2 error).
@Suite(.serialized, .timeLimit(.minutes(3))) struct PatternFamilyRendererRExecutionTests {

    private static var hasRscript: Bool {
        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        proc.arguments = ["Rscript", "--version"]
        proc.standardOutput = Pipe()
        proc.standardError = Pipe()
        do {
            try proc.run()
            proc.waitUntilExit()
            return proc.terminationStatus == 0
        } catch {
            return false
        }
    }

    /// The canonical R runtime, read from the repo so the test exercises the
    /// same source the runner injects.
    private static func canonicalRuntime() throws -> String {
        let root = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()  // APITests
            .deletingLastPathComponent()  // Tests
            .deletingLastPathComponent()  // repo root
        return try String(
            contentsOf: root.appendingPathComponent("Tools/runner-support/test_runtime.R"),
            encoding: .utf8)
    }

    private func run(script: GeneratedScript, submission: String) throws -> Int32 {
        let fm = FileManager.default
        let dir = fm.temporaryDirectory.appendingPathComponent("ck-rfam-\(UUID().uuidString)")
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: dir) }

        try Self.canonicalRuntime().write(
            to: dir.appendingPathComponent("test_runtime.R"), atomically: true, encoding: .utf8)
        try submission.write(
            to: dir.appendingPathComponent("solution.R"), atomically: true, encoding: .utf8)
        let scriptURL = dir.appendingPathComponent(script.filename)
        try script.source.write(to: scriptURL, atomically: true, encoding: .utf8)

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        proc.arguments = ["Rscript", scriptURL.path]
        proc.currentDirectoryURL = dir
        proc.standardOutput = Pipe()
        proc.standardError = Pipe()
        try proc.run()
        proc.waitUntilExit()
        return proc.terminationStatus
    }

    private func single(
        kind: PatternKind, functionName: String, paramNames: [String],
        args: [JSONValue], expected: JSONValue, defaults: PatternDefaults = PatternDefaults()
    ) -> GeneratedScript {
        let fam = PatternFamily(
            id: "fam", name: "Fam", kind: kind, functionName: functionName,
            paramNames: paramNames, defaults: defaults,
            cases: [PatternCase(key: "01", label: "Case 1", args: args, expected: expected)])
        // swiftlint:disable:next force_unwrapping
        return renderPatternFamily(fam, language: .r).first!
    }

    @Test func boundaryEqualityPassesAndFails() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .boundaryEquality, functionName: "double_it", paramNames: ["x"],
            args: [.int(21)], expected: .int(42))
        #expect(try run(script: script, submission: "double_it <- function(x) x * 2\n") == 0)
        #expect(try run(script: script, submission: "double_it <- function(x) x + 2\n") == 1)
        // Missing function -> errored (exit 2) via chickadee_require_fn.
        #expect(try run(script: script, submission: "other <- function(x) x\n") == 2)
    }

    @Test func boundaryEqualityComparesCollections() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .boundaryEquality, functionName: "letters_of", paramNames: ["s"],
            args: [.string("ab")], expected: .array([.string("a"), .string("b")]))
        #expect(
            try run(
                script: script,
                submission: "letters_of <- function(s) strsplit(s, \"\")[[1]]\n") == 0)
        #expect(
            try run(script: script, submission: "letters_of <- function(s) c(\"b\", \"a\")\n") == 1)
    }

    /// An integer return against a JSON-decoded double expectation must pass —
    /// the reason `chickadee_equal` compares numerics by value.
    @Test func integerReturnMatchesDoubleExpectation() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .boundaryEquality, functionName: "count", paramNames: ["x"],
            args: [.int(3)], expected: .int(3))
        #expect(try run(script: script, submission: "count <- function(x) 3L\n") == 0)
    }

    @Test func approximateEqualityHonoursTolerance() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .approximateEquality, functionName: "ratio", paramNames: ["x"],
            args: [.int(3)], expected: .double(0.3333333),
            defaults: PatternDefaults(tolerance: 1e-4))
        #expect(try run(script: script, submission: "ratio <- function(x) 1 / x\n") == 0)
        #expect(try run(script: script, submission: "ratio <- function(x) 0.5\n") == 1)
        // Non-numeric return is a clean failure, not an R error.
        #expect(try run(script: script, submission: "ratio <- function(x) \"nope\"\n") == 1)
    }

    @Test func unorderedEqualityIgnoresOrder() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .unorderedEquality, functionName: "tags", paramNames: ["x"],
            args: [.int(1)], expected: .array([.string("a"), .string("b"), .string("c")]))
        #expect(try run(script: script, submission: "tags <- function(x) c(\"c\",\"b\",\"a\")\n") == 0)
        #expect(try run(script: script, submission: "tags <- function(x) c(\"a\",\"b\")\n") == 1)
    }

    @Test func variableEqualityChecksModuleLevelValue() throws {
        guard Self.hasRscript else { return }
        let fam = PatternFamily(
            id: "fam", name: "Fam", kind: .variableEquality, functionName: "",
            cases: [
                PatternCase(key: "01", label: "beats", args: [.string("beats")], expected: .int(5))
            ])
        let script = try #require(renderPatternFamily(fam, language: .r).first)
        #expect(try run(script: script, submission: "beats <- 5\n") == 0)
        #expect(try run(script: script, submission: "beats <- 4\n") == 1)
        #expect(try run(script: script, submission: "other <- 5\n") == 1)
    }

    @Test func returnTypeCheckAcceptsRAndPythonTypeNames() throws {
        guard Self.hasRscript else { return }
        let rName = single(
            kind: .returnTypeCheck, functionName: "label", paramNames: ["x"],
            args: [.int(1)], expected: .string("character"))
        #expect(try run(script: rName, submission: "label <- function(x) \"hi\"\n") == 0)
        #expect(try run(script: rName, submission: "label <- function(x) 1\n") == 1)

        // A family converted from a Python assignment keeps working.
        let pyName = single(
            kind: .returnTypeCheck, functionName: "label", paramNames: ["x"],
            args: [.int(1)], expected: .string("str"))
        #expect(try run(script: pyName, submission: "label <- function(x) \"hi\"\n") == 0)
    }

    @Test func exceptionExpectedRequiresAnError() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .exceptionExpected, functionName: "boom", paramNames: ["x"],
            args: [.int(-1)], expected: .string("negative"))
        #expect(
            try run(
                script: script,
                submission: "boom <- function(x) if (x < 0) stop(\"negative input\") else x\n") == 0)
        // Succeeds when it should have raised.
        #expect(try run(script: script, submission: "boom <- function(x) x\n") == 1)
        // Raises, but not the expected error.
        #expect(try run(script: script, submission: "boom <- function(x) stop(\"other\")\n") == 1)
    }

    @Test func performanceThresholdBoundsRuntime() throws {
        guard Self.hasRscript else { return }
        // A tight budget keeps the over-budget case cheap: sleeping just past
        // it costs a fraction of a second rather than seconds of extra load on
        // a parallel test run (docs/ci-flakiness.md — subprocess-spawning
        // suites are what starve the slower app-backed suites).
        let script = single(
            kind: .performanceThreshold, functionName: "work", paramNames: ["n"],
            args: [.int(10)], expected: .int(150))
        #expect(try run(script: script, submission: "work <- function(n) sum(1:n)\n") == 0)
        #expect(try run(script: script, submission: "work <- function(n) { Sys.sleep(0.4); n }\n") == 1)
    }

    @Test func stdoutEqualityComparesPrintedOutput() throws {
        guard Self.hasRscript else { return }
        let script = single(
            kind: .stdoutEquality, functionName: "greet", paramNames: ["name"],
            args: [.string("Ada")], expected: .string("Hello, Ada!"))
        #expect(
            try run(
                script: script,
                submission: "greet <- function(name) cat(paste0(\"Hello, \", name, \"!\\n\"))\n") == 0)
        // Trailing blank lines / trailing spaces are normalized away.
        #expect(
            try run(
                script: script,
                submission: "greet <- function(name) cat(\"Hello, Ada!  \\n\\n\")\n") == 0)
        #expect(try run(script: script, submission: "greet <- function(name) cat(\"Bye\\n\")\n") == 1)
    }

    @Test func existenceGuardRunsForReal() throws {
        guard Self.hasRscript else { return }
        let fam = PatternFamily(
            id: "fam", name: "Fam", kind: .boundaryEquality, functionName: "solve",
            paramNames: ["x"],
            cases: [PatternCase(key: "01", label: "c", args: [.int(1)], expected: .int(1))])
        let script = try #require(existenceGuard(for: fam, language: .r))
        #expect(try run(script: script, submission: "solve <- function(x) x\n") == 0)
        #expect(try run(script: script, submission: "solve <- 42\n") == 1)
        #expect(try run(script: script, submission: "nothing <- 1\n") == 1)
    }

    /// End-to-end personalization: the value the server resolved lands in
    /// `_ck_inputs.R`, and the generated case binds it as `expected`.
    @Test func perStudentExpectedComesFromInputsFile() throws {
        guard Self.hasRscript else { return }
        let c = PatternCase(
            key: "01", label: "personalized", args: [.int(1)], expected: .null,
            expectedVarRef: "target")
        let fam = PatternFamily(
            id: "fam", name: "Fam", kind: .boundaryEquality, functionName: "answer",
            paramNames: ["x"], cases: [c])
        let script = try #require(
            renderPatternFamily(fam, perStudentNames: ["target"], language: .r).first)

        let fm = FileManager.default
        let dir = fm.temporaryDirectory.appendingPathComponent("ck-rfam-\(UUID().uuidString)")
        try fm.createDirectory(at: dir, withIntermediateDirectories: true)
        defer { try? fm.removeItem(at: dir) }
        try Self.canonicalRuntime().write(
            to: dir.appendingPathComponent("test_runtime.R"), atomically: true, encoding: .utf8)
        try "answer <- function(x) 7\n".write(
            to: dir.appendingPathComponent("solution.R"), atomically: true, encoding: .utf8)
        try AssignmentLanguage.r.renderInputsFile(["target": "7"]).write(
            to: dir.appendingPathComponent("_ck_inputs.R"), atomically: true, encoding: .utf8)
        let scriptURL = dir.appendingPathComponent(script.filename)
        try script.source.write(to: scriptURL, atomically: true, encoding: .utf8)

        let proc = Process()
        proc.executableURL = URL(fileURLWithPath: "/usr/bin/env")
        proc.arguments = ["Rscript", scriptURL.path]
        proc.currentDirectoryURL = dir
        proc.standardOutput = Pipe()
        proc.standardError = Pipe()
        try proc.run()
        proc.waitUntilExit()
        #expect(proc.terminationStatus == 0, "expected 7 delivered via _ck_inputs.R")
    }
}
