#!/bin/sh
# Generated by Chickadee — do not edit. The C++ source below is the
# test; this wrapper locates the submission, compiles one translation
# unit with the injected runtime, and runs it under the ordinary
# shell-script contract.
student_file=""
if [ -f .chickadee_student_module ]; then
    student_file=$(cat .chickadee_student_module)
fi
if [ ! -f "$student_file" ]; then
    # POSIX `*` does not match a leading dot, so every artefact this
    # wrapper writes (.ck_src_*, .ck_bin_*, .ck_solution.cpp) is already
    # invisible here — the `.ck_*` arm this case once carried matched
    # nothing and has been removed rather than left reading as a guard.
    # `*test_*` still skips a hand-written test file.
    for candidate in *.cpp; do
        case "$candidate" in
            *test_*) ;;
            *) student_file="$candidate"; break ;;
        esac
    done
fi
if [ ! -f "$student_file" ]; then
    echo "No C++ submission file was found to grade." 1>&2
    exit 2
fi
cp "$student_file" .ck_solution.cpp
cat > '.ck_src_fam_01.cpp' <<'CHICKADEE_GENERATED_SOURCE'
// Generated by Chickadee — pattern family 'fam', case '01' (s).
// Edit the family, not this file. spec_hash: fc8371b5e923b61d
#include "test_runtime.hpp"
#define main ck_student_main
#include ".ck_solution.cpp"
#undef main
int main() {
    auto x = 1;
    try {
        auto expected = std::string("hello");
        ck::CaptureStdout ck_capture;
        (void)classify(x);
        auto ck_printed = ck_capture.finish();
        // Trailing-newline tolerance, matching the other stdout renderers.
        while (!ck_printed.empty() && (ck_printed.back() == '\n' || ck_printed.back() == '\r')) {
            ck_printed.pop_back();
        }
        std::string ck_wanted(expected);
        while (!ck_wanted.empty() && (ck_wanted.back() == '\n' || ck_wanted.back() == '\r')) {
            ck_wanted.pop_back();
        }
        if (ck_printed != ck_wanted) {
            ck::failed(std::string("wrong output\n")
                + "  input:    " + "x=" + ck::format(x) + "\n"
                + "  expected: " + ck::format(ck_wanted) + "\n"
                + "  got:      " + ck::format(ck_printed));
        }
        ck::passed("Printed the expected output");
    } catch (const std::exception& ck_e) {
        ck::failed(std::string("unexpected exception\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  error:    " + ck_e.what());
    } catch (...) {
        ck::failed(std::string("unexpected exception\n")
            + "  input:    " + "x=" + ck::format(x) + "\n"
            + "  error:    (a non-std exception)");
    }
}
CHICKADEE_GENERATED_SOURCE
if ! g++ -std=c++20 -O0 '.ck_src_fam_01.cpp' -o '.ck_bin_fam_01' >.ck_build_log 2>&1; then
    cat .ck_build_log 1>&2
    exit 2
fi
exec './.ck_bin_fam_01'
