name: Worker Tests

on:
  workflow_dispatch:
  schedule:
    # 06:30 UTC is 2:30 AM in Toronto during daylight saving time.
    - cron: "30 6 * * *"

jobs:
  worker-tests:
    uses: ./.github/workflows/worker-tests-reusable.yml
